package com.abhiram.devquiz

import androidx.compose.ui.graphics.Color

enum class Topic(val label: String, val color: Color) {
    RENDER("RENDER", Color(0xFF61DAFB)),
    STATE("STATE", Color(0xFFA78BFA)),
    PERF("PERF", Color(0xFFFBBF24)),
    TYPES("TYPES", Color(0xFF60A5FA)),
    RUNTIME("RUNTIME", Color(0xFFF472B6)),
    DESIGN("DESIGN", Color(0xFF4ADE80)),
    DEBUG("DEBUG", Color(0xFFFB923C)),
    CODE("CODE", Color(0xFF2DD4BF)),
}

class Question(
    val topic: Topic,
    val prompt: String,
    val correct: String,
    val wrong: String,
    val why: String,
) {
    val id: Int = prompt.hashCode()
}

private fun q(topic: Topic, prompt: String, correct: String, wrong: String, why: String) =
    Question(topic, prompt, correct, wrong, why)

object Questions {

    val all: List<Question> = listOf(

        q(
            Topic.RENDER,
            "You call setCount in a click handler. Reading count on the next line gives you",
            "the old value",
            "the new value",
            "State is a snapshot per render. The update is queued and applies on the next render.",
        ),
        q(
            Topic.RENDER,
            "setN(n + 1) twice in one handler moves n by",
            "1",
            "2",
            "Both reads see the same snapshot. Use the updater form setN(c => c + 1) to stack them.",
        ),
        q(
            Topic.RENDER,
            "Which phase can React abort and restart",
            "render",
            "commit",
            "Render must be pure because it can be thrown away. Commit is one synchronous pass.",
        ),
        q(
            Topic.RENDER,
            "Array index as key on a reorderable list breaks",
            "child state lands on the wrong row",
            "nothing, you just get a warning",
            "Identity becomes positional, so React reuses the instance and its state for a different item.",
        ),
        q(
            Topic.RENDER,
            "Keys must be unique",
            "among siblings",
            "across the whole app",
            "Reconciliation only compares children of the same parent at the same position.",
        ),
        q(
            Topic.RENDER,
            "React throws away an instance and mounts fresh when",
            "the key or element type at that position changes",
            "any prop changes",
            "Same type plus same key means reuse. Everything else is a props update.",
        ),
        q(
            Topic.RENDER,
            "Force a remount without touching the parent",
            "change the child key",
            "call forceUpdate",
            "A new key makes it a different element at that position, so state is discarded.",
        ),
        q(
            Topic.RENDER,
            "When deps change, useEffect runs",
            "previous cleanup, then the new effect",
            "the new effect, then previous cleanup",
            "React always tears down the old subscription before setting up the new one.",
        ),
        q(
            Topic.RENDER,
            "useLayoutEffect fires",
            "after DOM mutation, before paint",
            "before React touches the DOM",
            "That is exactly why it can measure and correct layout with no visible flash.",
        ),
        q(
            Topic.RENDER,
            "The cost of useLayoutEffect is",
            "it blocks paint",
            "it skips batching",
            "Slow work there is jank the user sees as a frozen frame.",
        ),
        q(
            Topic.RENDER,
            "StrictMode double invokes effects to surface",
            "setup that is not safe to run twice",
            "components that render slowly",
            "It finds missing cleanup, the bug that shows up later as a leak or a duplicate subscription.",
        ),
        q(
            Topic.RENDER,
            "Tearing is",
            "one render reading two values of the same store",
            "a component unmounting mid animation",
            "Concurrent render can be interrupted, so an external store can change halfway through.",
        ),
        q(
            Topic.RENDER,
            "useSyncExternalStore exists because",
            "external stores are invisible to Reacts scheduler",
            "subscriptions were too slow",
            "It gives React a way to check for a change and bail out instead of tearing.",
        ),
        q(
            Topic.RENDER,
            "setInterval inside useEffect with empty deps reads",
            "state from the first render, forever",
            "the latest state",
            "The callback closed over that render scope. Nothing reruns to give it a new one.",
        ),
        q(
            Topic.RENDER,
            "Fix a stale interval WITHOUT tearing it down each tick",
            "the updater form setC(c => c + 1)",
            "add the value to the deps array",
            "The updater gets the current value from React, so the effect never needs to rerun.",
        ),
        q(
            Topic.RENDER,
            "Stale closure fix when you need the whole latest callback",
            "store it in a ref and read ref.current",
            "wrap it in useCallback",
            "useCallback still returns a function closed over one render. A ref is a mutable box.",
        ),
        q(
            Topic.RENDER,
            "Render must be pure because",
            "it may run more than once and be discarded",
            "React caches the returned JSX",
            "Side effects in render happen an unpredictable number of times.",
        ),
        q(
            Topic.RENDER,
            "React.memo compares",
            "props, shallowly",
            "the rendered output",
            "A new object or inline function prop defeats it every time.",
        ),
        q(
            Topic.RENDER,
            "useMemo is actively harmful when",
            "the compare costs more than the work",
            "the deps array is long",
            "You pay a comparison plus retained memory to avoid an addition.",
        ),
        q(
            Topic.RENDER,
            "useCallback around a prop to a non memoized child",
            "adds cost and prevents nothing",
            "still avoids the rerender",
            "The child rerenders with the parent anyway. Stability only matters to memo or a dep array.",
        ),
        q(
            Topic.RENDER,
            "Derived state should be",
            "computed during render",
            "written to state in an effect",
            "An effect adds a second render pass and a frame where the UI is inconsistent.",
        ),
        q(
            Topic.RENDER,
            "React 18 batches updates in",
            "promises and timeouts too",
            "only React event handlers",
            "Automatic batching extended past the event system in 18.",
        ),
        q(
            Topic.RENDER,
            "A components hook state actually lives",
            "on the fiber for that tree position",
            "in a map keyed by component name",
            "This is why the same component in two places has two independent states.",
        ),
        q(
            Topic.RENDER,
            "Hooks cannot be conditional because they are matched by",
            "call order",
            "variable name",
            "React walks a list per fiber. Skipping one shifts every hook after it.",
        ),
        q(
            Topic.RENDER,
            "A context value change reruns",
            "every consumer",
            "only consumers whose props changed",
            "Context has no selector. memo on the way down does not stop it.",
        ),
        q(
            Topic.RENDER,
            "Reconciliation compares children by",
            "type and key at the same position",
            "a deep diff of the whole subtree",
            "It is a single pass heuristic, which is why keys carry so much weight.",
        ),
        q(
            Topic.RENDER,
            "Suspense shows a fallback when a child",
            "throws a promise while rendering",
            "returns null",
            "The thrown promise is the signal. The boundary retries when it resolves.",
        ),
        q(
            Topic.RENDER,
            "Reading a ref during render is unsafe because",
            "it is mutable state outside the render snapshot",
            "refs are always null in render",
            "Two renders can see different values, which is tearing with extra steps.",
        ),

        q(
            Topic.STATE,
            "The rule for calling something server state",
            "the server owns the truth and it can go stale",
            "it arrived through fetch",
            "Ownership decides the tool. Stale truth needs caching and revalidation, not a reducer.",
        ),
        q(
            Topic.STATE,
            "State that belongs in the URL",
            "anything worth bookmarking or sharing",
            "nothing, URLs are only for routes",
            "Filters, tab, page and sort in the URL make reload and back work for free.",
        ),
        q(
            Topic.STATE,
            "Stale while revalidate means",
            "serve the cache now, refetch behind it",
            "block until fresh data arrives",
            "Instant paint plus eventual correctness, at the cost of a brief wrong value.",
        ),
        q(
            Topic.STATE,
            "After a mutation you should",
            "mark related queries stale",
            "clear the whole cache",
            "Invalidation refetches only what is observed. Clearing everything causes a spinner storm.",
        ),
        q(
            Topic.STATE,
            "An optimistic update needs",
            "a snapshot taken before the change",
            "a retry loop",
            "Rollback is impossible without the previous value.",
        ),
        q(
            Topic.STATE,
            "Two optimistic mutations on one entity can",
            "roll back to a snapshot containing the other change",
            "never conflict",
            "Snapshots overlap. You need per mutation context or a single serialized queue.",
        ),
        q(
            Topic.STATE,
            "Context is a poor fit for fast changing state because",
            "there is no selector, so all consumers rerender",
            "context is not memoized",
            "The propagation is all or nothing by design.",
        ),
        q(
            Topic.STATE,
            "Best fix for context causing wide rerenders",
            "split stable actions from changing values",
            "wrap consumers in React.memo",
            "memo cannot block context propagation. Splitting the provider actually reduces it.",
        ),
        q(
            Topic.STATE,
            "Search as you type breaks when",
            "an older response resolves last",
            "requests always resolve in order",
            "Network order is not request order. The stale result wins and overwrites the new one.",
        ),
        q(
            Topic.STATE,
            "Correct guard against out of order responses",
            "ignore anything not from the latest request",
            "raise the debounce delay",
            "Debouncing reduces the odds. It does not make the race impossible.",
        ),
        q(
            Topic.STATE,
            "Typeahead wants",
            "debounce",
            "throttle",
            "Only the final value matters, so collapse the burst instead of sampling it.",
        ),
        q(
            Topic.STATE,
            "A request waterfall is",
            "a child fetch that cannot start until the parent resolves",
            "too many requests at once",
            "Latency adds up per level instead of overlapping.",
        ),
        q(
            Topic.STATE,
            "Flatten a waterfall by",
            "hoisting data requirements so fetches start together",
            "adding a spinner per level",
            "Route level loaders or a single query for the screen turn serial latency into parallel.",
        ),
        q(
            Topic.STATE,
            "What forces a client component",
            "state, effects, refs, or event handlers",
            "importing a third party package",
            "Interactivity and browser APIs are the boundary, not where a package came from.",
        ),
        q(
            Topic.STATE,
            "Five requests get 401 at once. Correct handling",
            "one shared refresh they all await",
            "each retries its own refresh",
            "Five refreshes race and four of them invalidate the token the first one just minted.",
        ),
        q(
            Topic.STATE,
            "Token refresh belongs",
            "in one interceptor that queues failures",
            "in each component that fetches",
            "Centralizing it is the only way to dedupe the refresh and replay the queue.",
        ),
        q(
            Topic.STATE,
            "Before reaching for a store",
            "lift state up and see if that is enough",
            "add the store, it scales better",
            "The boring option costs nothing to remove later. A store is a dependency forever.",
        ),
        q(
            Topic.STATE,
            "Normalizing cached entities buys you",
            "one update propagating everywhere it appears",
            "a smaller bundle",
            "Duplicated nested copies drift, and you end up patching the same record in four caches.",
        ),
        q(
            Topic.STATE,
            "Refetch on window focus exists because",
            "the user was away and the truth may have moved",
            "it keeps the connection warm",
            "It is the cheapest approximation of realtime for data that does not need a socket.",
        ),
        q(
            Topic.STATE,
            "Form state usually belongs",
            "local or uncontrolled until submit",
            "in global state so anything can read it",
            "Global form state means every keystroke rerenders every subscriber.",
        ),
        q(
            Topic.STATE,
            "A mutation invalidating a list the user is not looking at",
            "refetches lazily when that list is next observed",
            "must refetch immediately",
            "Marking stale beats eager refetching for screens nobody is on.",
        ),
        q(
            Topic.STATE,
            "The point of a query key",
            "identity for dedupe, cache and invalidation",
            "a label for devtools",
            "Two components with the same key share one request and one cache entry.",
        ),

        q(
            Topic.PERF,
            "A page feels slow. Step one",
            "measure and find the long tasks",
            "memoize the heaviest components",
            "Optimizing before measuring is guessing, and it usually adds code that does nothing.",
        ),
        q(
            Topic.PERF,
            "One slow render versus many rerenders shows up as",
            "one wide bar versus many narrow bars",
            "you cannot tell them apart",
            "The flame chart shape tells you which class of fix applies before you touch code.",
        ),
        q(
            Topic.PERF,
            "Too many rerenders is fixed by",
            "cutting what triggers them",
            "making each render faster",
            "Split state, narrow context, stabilize props. Speed per render is the other problem.",
        ),
        q(
            Topic.PERF,
            "One slow render is fixed by",
            "doing less work in it",
            "wrapping the parent in memo",
            "Virtualize, hoist the computation, or move it off the main thread.",
        ),
        q(
            Topic.PERF,
            "A big bundle mostly hurts",
            "time to interactive",
            "steady state render speed",
            "Parse and execute block the main thread before your app can respond to anything.",
        ),
        q(
            Topic.PERF,
            "INP measures",
            "response and paint after an interaction",
            "time to first byte",
            "It is about how the app feels under the finger, not how fast the server answered.",
        ),
        q(
            Topic.PERF,
            "INP is the hard one in SPAs because",
            "long tasks delay the response to a tap",
            "images load slowly",
            "Any single task over 50ms is a queue the users tap has to wait behind.",
        ),
        q(
            Topic.PERF,
            "Virtualizing variable height rows requires",
            "measured heights cached per item",
            "one fixed estimate is enough",
            "Estimates make the scrollbar and the offsets lie once real heights resolve.",
        ),
        q(
            Topic.PERF,
            "Virtualization silently breaks",
            "browser find in page",
            "nothing, it is transparent",
            "Offscreen rows are not in the DOM, so ctrl F, screen readers and anchors miss them.",
        ),
        q(
            Topic.PERF,
            "A context value rebuilt every render",
            "rerenders every consumer every time",
            "only rerenders the provider",
            "The identity changed, so context propagates even though the data did not.",
        ),
        q(
            Topic.PERF,
            "Avoid a spinner cascade by",
            "hoisting boundaries and prefetching per route",
            "shortening each spinners delay",
            "Many small boundaries mean many sequential reveals. Fewer, higher boundaries feel faster.",
        ),
        q(
            Topic.PERF,
            "Best code split boundary for a dashboard",
            "per route, then per heavy widget behind interaction",
            "per component file",
            "Splitting everything trades one big download for a hundred round trips.",
        ),
        q(
            Topic.PERF,
            "useDeferredValue lets you",
            "keep the input snappy while the list lags behind",
            "debounce by a fixed delay",
            "It is priority based, not time based, so it adapts to how slow the render actually is.",
        ),
        q(
            Topic.PERF,
            "useTransition versus useDeferredValue",
            "transition wraps an update you own, deferred wraps a value you receive",
            "they are the same thing",
            "Pick by whether you control the setState or only see the prop.",
        ),
        q(
            Topic.PERF,
            "Filtering 50k rows on every keystroke",
            "blocks paint, move it to a worker or the server",
            "is solved by useMemo",
            "useMemo skips repeat work. It does not make the one necessary pass non blocking.",
        ),
        q(
            Topic.PERF,
            "A web worker cannot",
            "touch the DOM",
            "call fetch",
            "It has no document. Messages are cloned, so shared object identity is gone too.",
        ),
        q(
            Topic.PERF,
            "CLS is caused by",
            "content inserted or resized without reserved space",
            "slow JavaScript",
            "Reserve dimensions for images, ads and late loading banners.",
        ),
        q(
            Topic.PERF,
            "The most reliable perf win, usually",
            "ship less JS and render less DOM",
            "memoize more components",
            "Memoization is a local patch. Volume is the thing that actually costs frames.",
        ),
        q(
            Topic.PERF,
            "React DevTools Profiler tells you",
            "which components rendered and why",
            "which network calls were slow",
            "Use the Profiler for render cost and the Performance panel for long tasks.",
        ),
        q(
            Topic.PERF,
            "An inline object prop defeats memo because",
            "shallow compare sees a new reference",
            "memo ignores object props",
            "Same contents, different identity, so the compare fails every render.",
        ),

        q(
            Topic.TYPES,
            "Only interfaces can",
            "be reopened and merged",
            "extend other types",
            "Declaration merging is the one real capability difference. Both extend fine.",
        ),
        q(
            Topic.TYPES,
            "Declaration merging matters when",
            "you augment a type you do not own",
            "you want less code",
            "Adding to a global, a module, or a library type is the actual use case.",
        ),
        q(
            Topic.TYPES,
            "unknown versus any",
            "unknown forces a check before use",
            "they behave the same",
            "any deletes the type system locally and spreads. unknown makes you prove the shape.",
        ),
        q(
            Topic.TYPES,
            "never means",
            "a value that cannot exist",
            "null or undefined",
            "It marks unreachable code, which is what makes exhaustiveness checks work.",
        ),
        q(
            Topic.TYPES,
            "never shows up unintentionally when",
            "a union narrows until nothing is left",
            "you omit a return type",
            "Also from an empty array literal, which infers never and rejects every push.",
        ),
        q(
            Topic.TYPES,
            "A callback with fewer parameters is assignable because",
            "extra arguments are safely ignored at runtime",
            "it is an unsoundness bug",
            "Array.map(x => x) works precisely because of this rule.",
        ),
        q(
            Topic.TYPES,
            "Method syntax parameters are compared",
            "bivariantly",
            "contravariantly, like function properties",
            "Methods stay bivariant for compatibility, so strictFunctionTypes does not cover them.",
        ),
        q(
            Topic.TYPES,
            "Exactly one of two props, never both",
            "a discriminated union of two shapes",
            "both optional plus a runtime check",
            "Optional plus optional lets the impossible combination compile.",
        ),
        q(
            Topic.TYPES,
            "Enforce an exhaustive switch by",
            "assigning the value to never in the default branch",
            "adding a lint rule",
            "Adding a union member then becomes a compile error at every switch that forgot it.",
        ),
        q(
            Topic.TYPES,
            "DeepPartial is dangerous because",
            "it hides genuinely missing nested data",
            "it only slows the compiler",
            "Every field becomes optional, so the checker stops asking whether you built a valid object.",
        ),
        q(
            Topic.TYPES,
            "infer is used to",
            "capture a type from inside a conditional type",
            "give a generic a default",
            "It is how ReturnType, Awaited and Parameters are written.",
        ),
        q(
            Topic.TYPES,
            "ReturnType of an async function gives",
            "a Promise, so you need Awaited",
            "the resolved value",
            "async always wraps. Awaited unwraps through nested promises.",
        ),
        q(
            Topic.TYPES,
            "A generic constrained to have an id lets you",
            "read id inside while keeping the callers exact type",
            "treat T as exactly that object",
            "This is the whole point of a constraint over a concrete parameter type.",
        ),
        q(
            Topic.TYPES,
            "A polymorphic as prop needs",
            "a generic element type plus its own props",
            "props typed as any",
            "ComponentPropsWithoutRef of the generic is what keeps href checked when as is a link.",
        ),
        q(
            Topic.TYPES,
            "A branded type is",
            "a base type intersected with a unique marker",
            "a class wrapper",
            "It costs nothing at runtime and makes two string ids stop being interchangeable.",
        ),
        q(
            Topic.TYPES,
            "Brand a UserId so that",
            "an OrderId cannot be passed in its place",
            "it is shorter to write",
            "Structural typing sees both as string. The brand is what makes them distinct.",
        ),
        q(
            Topic.TYPES,
            "Structural typing decides compatibility by",
            "shape",
            "declared name",
            "Anything with the right members fits, whether or not it says it implements the interface.",
        ),
        q(
            Topic.TYPES,
            "satisfies gives you",
            "the check plus the narrow inferred literals",
            "a runtime assertion",
            "An annotation would widen the value to the declared type and lose the literal keys.",
        ),
        q(
            Topic.TYPES,
            "Casting a fetch response with as is a lie because",
            "nothing validates the bytes at runtime",
            "casts are slow",
            "The crash then lands far from the fetch, in whatever read the missing field.",
        ),
        q(
            Topic.TYPES,
            "Runtime validation belongs",
            "at the boundary, parsed once",
            "in each component that reads the data",
            "Parse once into a trusted type and the rest of the app can rely on the compiler again.",
        ),
        q(
            Topic.TYPES,
            "Stop the type gymnastics when",
            "the type is harder to read than the bug it prevents",
            "never, more types is always better",
            "Compile time and the next reader are both real costs.",
        ),
        q(
            Topic.TYPES,
            "Indexing a Record with a missing key returns",
            "T, unless noUncheckedIndexedAccess is on",
            "T or undefined, always",
            "This is the default unsoundness that produces cannot read property of undefined.",
        ),
        q(
            Topic.TYPES,
            "readonly arrays are",
            "compile time only",
            "frozen at runtime",
            "Nothing is enforced once it ships. Use Object.freeze if you need actual immutability.",
        ),
        q(
            Topic.TYPES,
            "import type guarantees",
            "the import is erased",
            "better inference",
            "It prevents a runtime require, which kills accidental cycles and side effects.",
        ),
        q(
            Topic.TYPES,
            "any is worse than a cast because",
            "it disables checks on everything downstream",
            "it is local to that annotation",
            "It propagates through every expression it touches, silently.",
        ),
        q(
            Topic.TYPES,
            "Overloads beat a union parameter when",
            "the return type depends on which shape came in",
            "you want documentation",
            "A union parameter cannot express that correlation between argument and result.",
        ),
        q(
            Topic.TYPES,
            "A type predicate function is trusted",
            "on your word, it is unchecked",
            "verified by the compiler",
            "A wrong predicate is a silent lie, so keep the body trivial and obviously right.",
        ),
        q(
            Topic.TYPES,
            "Excess property checks apply to",
            "fresh object literals only",
            "every assignment",
            "Assign the literal to a variable first and the extra key sails through.",
        ),

        q(
            Topic.RUNTIME,
            "Between two macrotasks the engine",
            "drains the whole microtask queue",
            "runs one microtask",
            "This is why an endless chain of promises can starve rendering completely.",
        ),
        q(
            Topic.RUNTIME,
            "setTimeout zero versus a resolved promise then",
            "the promise callback runs first",
            "the timeout runs first",
            "Microtasks are drained before the next timer callback is even considered.",
        ),
        q(
            Topic.RUNTIME,
            "await splits the function so that",
            "the rest becomes a microtask continuation",
            "the thread blocks",
            "Nothing blocks. The remainder is scheduled and the stack unwinds.",
        ),
        q(
            Topic.RUNTIME,
            "Promise.all rejects",
            "on the first rejection, others keep running",
            "after everything settles",
            "The unobserved ones can still throw, which is a common unhandled rejection source.",
        ),
        q(
            Topic.RUNTIME,
            "allSettled is the one you need when",
            "partial success is a real outcome",
            "you want the fastest result",
            "Batch operations where three of five succeeding is still useful.",
        ),
        q(
            Topic.RUNTIME,
            "race versus any",
            "race takes the first to settle, any the first to fulfil",
            "they are identical",
            "race surfaces an early rejection. any ignores rejections until they all fail.",
        ),
        q(
            Topic.RUNTIME,
            "Keeping exactly N promises in flight",
            "N workers pulling from a shared list",
            "await a chunk of N in a loop",
            "Chunking waits for the slowest member of each batch before starting the next.",
        ),
        q(
            Topic.RUNTIME,
            "AbortController propagates by",
            "passing the same signal to every call",
            "cancelling anything started inside automatically",
            "There is no ambient cancellation. Signals are threaded through by hand.",
        ),
        q(
            Topic.RUNTIME,
            "Aborting a fetch",
            "rejects with an AbortError you must handle",
            "resolves with an empty response",
            "Treat AbortError as expected, not as a failure to report.",
        ),
        q(
            Topic.RUNTIME,
            "The most common SPA leak",
            "a subscription added with no removal",
            "too many components",
            "Listeners, intervals, observers and sockets outlive the component that made them.",
        ),
        q(
            Topic.RUNTIME,
            "A detached DOM node means",
            "JS still references a node removed from the document",
            "the node failed to render",
            "It is the classic heap snapshot signature of a listener or closure holding on.",
        ),
        q(
            Topic.RUNTIME,
            "Find a leak by",
            "comparing heap snapshots at the same app state",
            "watching the FPS meter",
            "Return to the same screen twice. Anything retained that grew is your suspect.",
        ),
        q(
            Topic.RUNTIME,
            "A module level cache leaks because",
            "it lives as long as the page and never evicts",
            "modules are collected per route",
            "Module scope is effectively global. Unbounded means unbounded.",
        ),
        q(
            Topic.RUNTIME,
            "this in a plain function call is",
            "undefined in strict mode",
            "always the enclosing object",
            "Losing this by extracting a method is why bind and arrow fields exist.",
        ),
        q(
            Topic.RUNTIME,
            "An arrow functions this is",
            "captured lexically and cannot be rebound",
            "bound at call time",
            "call, apply and bind cannot change it, which is the feature and the trap.",
        ),
        q(
            Topic.RUNTIME,
            "Arrow class fields create",
            "one function per instance",
            "one shared prototype method",
            "That is the memory cost you pay for automatic binding.",
        ),
        q(
            Topic.RUNTIME,
            "Generators let you",
            "pause and resume, yielding on demand",
            "run code on another thread",
            "Still single threaded. It is lazy control flow, not concurrency.",
        ),
        q(
            Topic.RUNTIME,
            "Async iterators fit",
            "streams and pagination",
            "CPU bound loops",
            "for await over pages hides the cursor plumbing without blocking.",
        ),
        q(
            Topic.RUNTIME,
            "Structured clone cannot copy",
            "functions and DOM nodes",
            "Maps and Sets",
            "Maps, Sets and Dates clone fine. Functions, nodes and class identity do not.",
        ),
        q(
            Topic.RUNTIME,
            "postMessage sends",
            "a copy, unless you transfer a buffer",
            "a live reference",
            "Transferring an ArrayBuffer moves ownership and empties it on the sending side.",
        ),
        q(
            Topic.RUNTIME,
            "The one defensible use of double equals",
            "x == null to catch null and undefined",
            "none, it is always wrong",
            "It is the single coercion that is both intentional and readable.",
        ),
        q(
            Topic.RUNTIME,
            "A closure captures",
            "the binding",
            "a snapshot of the value",
            "This is exactly why var in a loop gave everyone the final index.",
        ),
        q(
            Topic.RUNTIME,
            "try catch around a promise you did not await",
            "catches nothing",
            "catches the rejection",
            "The rejection happens after the block exited. Without await there is no stack to catch on.",
        ),
        q(
            Topic.RUNTIME,
            "An async function that throws",
            "returns a rejected promise",
            "throws synchronously",
            "Callers must await or catch. Nothing propagates up the synchronous stack.",
        ),
        q(
            Topic.RUNTIME,
            "Event loop starvation happens when",
            "microtasks keep queueing microtasks",
            "there are too many timers",
            "Timers yield. An endless microtask chain never lets the browser paint.",
        ),
        q(
            Topic.RUNTIME,
            "Object spread copies",
            "one level deep",
            "the whole object graph",
            "Nested objects stay shared, which is how accidental mutation crosses a boundary.",
        ),
        q(
            Topic.RUNTIME,
            "requestAnimationFrame runs",
            "before the next paint",
            "on a fixed 16ms timer",
            "It is tied to the frame, so it stops in a background tab.",
        ),
        q(
            Topic.RUNTIME,
            "Reading offsetHeight right after a style write causes",
            "a forced synchronous layout",
            "nothing measurable",
            "Interleaving reads and writes in a loop is layout thrashing. Batch reads first.",
        ),

        q(
            Topic.DESIGN,
            "Collaborative editing: local input should",
            "apply at once, then reconcile with the server order",
            "wait for the server to confirm",
            "Waiting per keystroke makes typing feel broken over any real network.",
        ),
        q(
            Topic.DESIGN,
            "Handle out of order realtime events by",
            "carrying a version and dropping anything older",
            "trusting arrival order",
            "Reconnects and retries deliver the past. Only a sequence number can tell you.",
        ),
        q(
            Topic.DESIGN,
            "After a socket reconnect you should",
            "refetch or replay from the last acked cursor",
            "keep local state and continue",
            "You do not know what you missed while disconnected, so assume you missed something.",
        ),
        q(
            Topic.DESIGN,
            "Composition over configuration means",
            "parts the caller assembles",
            "more props with good defaults",
            "One component with a flag per variation grows forever and cannot be composed out of.",
        ),
        q(
            Topic.DESIGN,
            "A component with thirty props signals",
            "variants that should be separate parts or slots",
            "a thoroughly documented API",
            "The prop count is the symptom. The cause is one component doing several jobs.",
        ),
        q(
            Topic.DESIGN,
            "Headless component libraries separate",
            "behavior and accessibility from styling",
            "server code from client code",
            "You get keyboard and aria correctness without inheriting someone elses visual design.",
        ),
        q(
            Topic.DESIGN,
            "Migrating a design system across 400 files",
            "run both systems and migrate incrementally",
            "one branch that converts everything",
            "A big bang branch cannot be reviewed, cannot be released safely, and never lands.",
        ),
        q(
            Topic.DESIGN,
            "The classic shared UI monorepo failure",
            "one bump forces every app to release together",
            "slower type checking",
            "Coupled release cadence is what actually stalls teams.",
        ),
        q(
            Topic.DESIGN,
            "Deprecating a component twelve teams use",
            "warn, ship a codemod, set a removal date",
            "delete it and announce the replacement",
            "Migration you do not automate is migration that does not happen.",
        ),
        q(
            Topic.DESIGN,
            "A forty field form stays fast when",
            "a keystroke rerenders one field",
            "the form object lives in context",
            "Uncontrolled fields or per field subscriptions keep the tree out of the keystroke path.",
        ),
        q(
            Topic.DESIGN,
            "Client and server validation relate as",
            "the server is authoritative, the client is a hint",
            "duplicate the rules and trust the client",
            "Client checks are for speed of feedback. They are never a guarantee.",
        ),
        q(
            Topic.DESIGN,
            "Feature flags avoid permanent rot by having",
            "an owner and a removal date",
            "the option to toggle them later",
            "Every flag is a live branch in the code. Without an expiry they all stay forever.",
        ),
        q(
            Topic.DESIGN,
            "Most test value per hour sits in",
            "integration tests against a faked network",
            "a unit test per function",
            "They exercise the wiring, which is where React apps actually break.",
        ),
        q(
            Topic.DESIGN,
            "You deliberately do not test",
            "implementation details like render counts",
            "error and empty states",
            "Tests coupled to internals block every refactor and catch nothing real.",
        ),
        q(
            Topic.DESIGN,
            "Error boundaries belong",
            "around each independently failing region",
            "once at the app root",
            "A root only boundary turns one broken widget into a blank page.",
        ),
        q(
            Topic.DESIGN,
            "Error boundaries do not catch",
            "errors in event handlers and async callbacks",
            "render errors in children",
            "They only see the render, lifecycle and constructor path.",
        ),
        q(
            Topic.DESIGN,
            "A custom dropdown needs, above all",
            "focus management and keyboard handling",
            "the right aria role attribute",
            "Roles describe. They do not implement behavior, and a wrong role is worse than none.",
        ),
        q(
            Topic.DESIGN,
            "Roving tabindex is for",
            "a composite widget with one tab stop",
            "skip to main content",
            "A grid or a toolbar should be one stop, then arrow keys inside.",
        ),
        q(
            Topic.DESIGN,
            "An aria live region",
            "announces changes the user did not trigger",
            "labels an element",
            "Toasts, validation summaries and background updates need it or they are silent.",
        ),
        q(
            Topic.DESIGN,
            "A correct modal must",
            "trap focus, restore it, hide the background",
            "autofocus the first input",
            "Restoring focus to the trigger on close is the part everybody forgets.",
        ),
        q(
            Topic.DESIGN,
            "Streaming plus error boundaries means",
            "a failed segment shows its own fallback inline",
            "the whole page falls back",
            "That is the payoff of putting boundaries around independent regions.",
        ),
        q(
            Topic.DESIGN,
            "The strongest argument for a shared package",
            "the behavior must not drift between apps",
            "the code is duplicated",
            "Duplication is cheap. Divergence in behavior is what actually hurts.",
        ),

        q(
            Topic.DEBUG,
            "First move on any bug",
            "reproduce it reliably",
            "read the code until you spot it",
            "Without a repro you cannot know your fix worked, only that the symptom went quiet.",
        ),
        q(
            Topic.DEBUG,
            "Works locally, fails in production. Look at",
            "what differs: build, env, data volume, caching",
            "the feature logic",
            "The code is the same. The environment is not, so start with the delta.",
        ),
        q(
            Topic.DEBUG,
            "A fix with no reproduction is",
            "a guess",
            "fine if tests pass",
            "Green tests that never covered the bug prove nothing about the bug.",
        ),
        q(
            Topic.DEBUG,
            "One customer only reproduces it. Assume",
            "their data or config is the variable",
            "their browser is broken",
            "Get the exact state. Single tenant bugs are almost always data shaped.",
        ),
        q(
            Topic.DEBUG,
            "Bisecting is powerful because",
            "it finds the commit without understanding the code",
            "it fixes regressions",
            "It converts an unbounded search through logic into a few builds.",
        ),
        q(
            Topic.DEBUG,
            "No tests plus a rewrite proposal. Recommend",
            "tests around current behavior, then refactor in place",
            "the rewrite, the code is unrecoverable",
            "A rewrite drops behavior nobody wrote down, and you discover it in production.",
        ),
        q(
            Topic.DEBUG,
            "You know an abstraction is wrong when",
            "each new case needs a flag or an escape hatch",
            "the file got long",
            "The parameter list growing per caller is the tell.",
        ),
        q(
            Topic.DEBUG,
            "Fix a wrong abstraction by",
            "inlining it back to duplication first",
            "adding an option for the new case",
            "Let the real shape appear from the duplicates instead of guessing again.",
        ),
        q(
            Topic.DEBUG,
            "A bug that vanishes when you add logging is",
            "timing or ordering dependent",
            "a compiler bug",
            "The log changed the timing. Look for a race, not a miscompile.",
        ),
        q(
            Topic.DEBUG,
            "After the fix lands",
            "add the failing case as a test",
            "close the ticket, it is fixed",
            "Otherwise the same regression returns silently in six months.",
        ),
        q(
            Topic.DEBUG,
            "The signal an interviewer wants on a perf question",
            "a diagnosis process",
            "a list of optimizations you know",
            "Measurement before optimization is the actual senior marker.",
        ),
        q(
            Topic.DEBUG,
            "Best first question on an intermittent failure",
            "what is shared between the failing runs",
            "how do I retry it",
            "Intermittent means a hidden variable. Find it before touching the code.",
        ),

        q(
            Topic.CODE,
            "A debounced autocomplete must handle",
            "loading, empty, error, and cancellation",
            "the results list",
            "The states you skip are exactly the ones the interviewer is watching for.",
        ),
        q(
            Topic.CODE,
            "Autocomplete keyboard support means",
            "arrows move an active index, enter selects, escape closes",
            "tab through the options",
            "Tab must leave the widget. Movement inside is arrows plus aria activedescendant.",
        ),
        q(
            Topic.CODE,
            "Dedupe in a hand rolled useQuery works by",
            "keying in flight promises and sharing them",
            "an isLoading boolean",
            "Two components mounting together must join one request, not fire two.",
        ),
        q(
            Topic.CODE,
            "Infinite scroll with IntersectionObserver uses",
            "a sentinel after the last row",
            "a scroll listener comparing offsets",
            "The observer reports intersections without you sampling scroll position.",
        ),
        q(
            Topic.CODE,
            "A sentinel beats a scroll handler because",
            "it does not run on the scroll path",
            "it is less code",
            "No throttling, no layout reads per frame, no jank while scrolling.",
        ),
        q(
            Topic.CODE,
            "A focus trap must",
            "cycle tab both ways and restore focus on close",
            "preventDefault on tab",
            "Blocking tab strands keyboard users. Cycling plus restore is the contract.",
        ),
        q(
            Topic.CODE,
            "Escape handling for a modal should be",
            "scoped and removed on unmount",
            "on document, left in place",
            "A leftover document listener closes the next modal too, or leaks.",
        ),
        q(
            Topic.CODE,
            "A drag handle should use",
            "pointer events with setPointerCapture",
            "mousemove on the element",
            "Capture keeps the drag alive when the cursor outruns the handle, and covers touch.",
        ),
        q(
            Topic.CODE,
            "debounce with cancel and flush needs",
            "the timer id and last arguments in the closure",
            "a module level map",
            "Each debounced function owns its pending call. A shared map collides.",
        ),
        q(
            Topic.CODE,
            "deepEqual has to handle",
            "cycles, NaN, Date and Map",
            "nested plain objects",
            "The interesting cases are the non plain ones, and cycles are where naive versions hang.",
        ),
        q(
            Topic.CODE,
            "A typed event emitter is keyed by",
            "a record of event name to payload type",
            "any as the payload",
            "That mapping is what keeps emit and on from drifting apart.",
        ),
        q(
            Topic.CODE,
            "Five useEffect calls in one component usually means",
            "derived values are being written to state",
            "the component does five real jobs",
            "Most of them collapse into plain computation during render.",
        ),
        q(
            Topic.CODE,
            "First question when refactoring an effect",
            "does this synchronize with something outside React",
            "can I merge the dep arrays",
            "If nothing external is involved it should not be an effect at all.",
        ),
        q(
            Topic.CODE,
            "throttle differs from debounce by",
            "guaranteeing a call every interval",
            "waiting for silence",
            "Use throttle when steady updates matter, debounce when only the last value does.",
        ),
        q(
            Topic.CODE,
            "Implementing useFetch, the cleanup must",
            "abort or ignore the in flight request",
            "clear the loading flag",
            "Otherwise a late response sets state on a component that moved on.",
        ),
        q(
            Topic.CODE,
            "A custom hook returning an object should",
            "keep a stable identity across renders",
            "rebuild it each render for freshness",
            "An unstable return value breaks every dep array downstream.",
        ),
    )
}
