package com.abhiram.devquiz

internal val tsArray: List<Question> = listOf(

    q(
        Topic.ARRAY,
        "[1, 2, 3]\n  .map(n => n * 2)",
        "Result?",
        "[2, 4, 6]",
        "6",
        "map returns a new array of the same length. reduce is the one that folds.",
    ),
    q(
        Topic.ARRAY,
        "[1, 2, 3]\n  .filter(n => n > 1)",
        "Result?",
        "[2, 3]",
        "true",
        "filter keeps the items where the test is truthy.",
    ),
    q(
        Topic.ARRAY,
        "[1, 2, 3].reduce(\n  (a, b) => a + b, 0)",
        "Result?",
        "6",
        "[6]",
        "The 0 is the seed. Without it reduce on an empty array throws.",
    ),
    q(
        Topic.ARRAY,
        "[].reduce(\n  (a, b) => a + b)",
        "Result?",
        "a TypeError",
        "0",
        "No seed and no items means there is nothing to start from.",
    ),
    q(
        Topic.ARRAY,
        "[1, 2].find(n => n > 5)",
        "Result?",
        "undefined",
        "-1",
        "find gives the item. findIndex is the one that gives -1.",
    ),
    q(
        Topic.ARRAY,
        "[1, 2].some(n => n > 1)\n[1, 2].every(n => n > 1)",
        "The two lines?",
        "true, then false",
        "true, then true",
        "some needs one match, every needs all of them.",
    ),
    q(
        Topic.ARRAY,
        "[].every(x => false)",
        "Result?",
        "true",
        "false",
        "every on an empty array is vacuously true. some is false.",
    ),
    q(
        Topic.ARRAY,
        "a.slice(1, 3)\na.splice(1, 3)",
        "Which mutates a?",
        "splice",
        "slice",
        "slice copies a window. splice cuts out of the original.",
    ),
    q(
        Topic.ARRAY,
        "[1, [2, [3]]].flat()",
        "Result?",
        "[1, 2, [3]]",
        "[1, 2, 3]",
        "flat goes one level by default. Pass Infinity for all of them.",
    ),
    q(
        Topic.ARRAY,
        "['a b'].flatMap(\n  s => s.split(' '))",
        "Result?",
        "['a', 'b']",
        "[['a', 'b']]",
        "flatMap is map then one level of flatten, which is exactly this case.",
    ),
    q(
        Topic.ARRAY,
        "[1, 2, 3].includes(2)",
        "Result?",
        "true",
        "1",
        "includes gives a boolean. indexOf gives the position.",
    ),
    q(
        Topic.ARRAY,
        "[NaN].includes(NaN)\n[NaN].indexOf(NaN)",
        "The two lines?",
        "true, then -1",
        "true, then 0",
        "includes uses a comparison that treats NaN as equal to itself.",
    ),
    q(
        Topic.ARRAY,
        "Array(3).fill(0)",
        "Result?",
        "[0, 0, 0]",
        "[3]",
        "Array(3) makes three holes. fill or Array.from makes them real.",
    ),
    q(
        Topic.ARRAY,
        "Array.from(\n  { length: 3 },\n  (_, i) => i)",
        "Result?",
        "[0, 1, 2]",
        "[3, 3, 3]",
        "The second argument is a map function over each index.",
    ),
    q(
        Topic.ARRAY,
        "const b = [...a]\nb[0].n = 1",
        "Does a change?",
        "yes, the objects are shared",
        "no, spread is deep",
        "Spread copies one level. The nested objects are the same references.",
    ),
    q(
        Topic.ARRAY,
        "[...new Set(arr)]",
        "This does?",
        "removes duplicates",
        "sorts the array",
        "The classic dedupe. It keeps first occurrence order.",
    ),
    q(
        Topic.ARRAY,
        "a.sort(\n  (x, y) => x.n - y.n)",
        "Ascending or descending?",
        "ascending",
        "descending",
        "Negative means x comes first, so subtracting the later one sorts up.",
    ),
    q(
        Topic.ARRAY,
        "a.toSorted()",
        "Compared to sort?",
        "returns a copy, leaves a alone",
        "the same thing",
        "toSorted, toReversed and with are the newer non mutating versions.",
    ),
    q(
        Topic.ARRAY,
        "[1, 2, 3].indexOf(4)",
        "Result?",
        "-1",
        "undefined",
        "-1 for a miss, which is why if (i) is a bug and if (i >= 0) is not.",
    ),
    q(
        Topic.ARRAY,
        "arr.join('-')",
        "On [1, null, 2]?",
        "'1--2'",
        "'1-null-2'",
        "join renders null and undefined as an empty string.",
    ),
    q(
        Topic.ARRAY,
        "const a = [1, 2]\na[5] = 6\na.length",
        "Result?",
        "6",
        "3",
        "Writing past the end stretches the array and leaves holes.",
    ),
    q(
        Topic.ARRAY,
        "arr.forEach(x => ...)",
        "Return value?",
        "undefined",
        "the new array",
        "forEach is for side effects only. map is the one that gives you a result.",
    ),
    q(
        Topic.ARRAY,
        "for (const x of arr)\nfor (const i in arr)",
        "Difference?",
        "of gives values, in gives keys",
        "they are the same",
        "in walks string keys, which is almost never what you want on an array.",
    ),
    q(
        Topic.ARRAY,
        "const m = new Map()\nm.set({}, 1).get({})",
        "Result?",
        "undefined",
        "1",
        "Two object literals are different keys. Map compares by identity.",
    ),
    q(
        Topic.ARRAY,
        "Object.entries(o)\n  .map(([k, v]) => k)",
        "Type of k?",
        "string",
        "keyof typeof o",
        "entries widens keys to string, which is why typed helpers exist.",
    ),
)

internal val tsObject: List<Question> = listOf(

    q(
        Topic.OBJECT,
        "const b = { ...a, n: 2 }",
        "If a already has n?",
        "the later 2 wins",
        "a's value wins",
        "Later keys overwrite earlier ones, so order in the literal matters.",
    ),
    q(
        Topic.OBJECT,
        "const { a, ...rest } = o",
        "rest is?",
        "o without a",
        "just a",
        "Rest in destructuring is the idiomatic way to drop one key.",
    ),
    q(
        Topic.OBJECT,
        "const { a: { b } } = o",
        "This binds?",
        "b only",
        "a and b",
        "Nested destructuring reaches through without binding the middle name.",
    ),
    q(
        Topic.OBJECT,
        "const key = 'n'\nconst o = { [key]: 1 }",
        "o is?",
        "{ n: 1 }",
        "{ key: 1 }",
        "Brackets in a literal evaluate the expression as the key.",
    ),
    q(
        Topic.OBJECT,
        "Object.keys({ a: 1 })",
        "Result?",
        "['a']",
        "[['a', 1]]",
        "keys gives names, values gives values, entries gives pairs.",
    ),
    q(
        Topic.OBJECT,
        "Object.freeze(o)\no.a.b = 1",
        "Does it change?",
        "yes, freeze is shallow",
        "no, it throws",
        "freeze locks the top level only, and silently unless in strict mode.",
    ),
    q(
        Topic.OBJECT,
        "'a' in o\no.a !== undefined",
        "Difference?",
        "in is true even for a: undefined",
        "none",
        "in asks whether the key exists at all, value aside.",
    ),
    q(
        Topic.OBJECT,
        "o.hasOwnProperty('a')",
        "Safer version?",
        "Object.hasOwn(o, 'a')",
        "o.a !== null",
        "hasOwn works even when the object has no prototype or shadows the method.",
    ),
    q(
        Topic.OBJECT,
        "const o = Object\n  .assign({}, a, b)",
        "Equivalent to?",
        "{ ...a, ...b }",
        "a deep merge",
        "Both are shallow and both let the later source win.",
    ),
    q(
        Topic.OBJECT,
        "delete o.a",
        "Result?",
        "removes the key entirely",
        "sets it to undefined",
        "The key is gone, so 'a' in o becomes false.",
    ),
    q(
        Topic.OBJECT,
        "const o = { a: 1 }\nconst p = o\np.a = 2\no.a",
        "Result?",
        "2",
        "1",
        "Both names point at the same object. Copy it before you edit.",
    ),
    q(
        Topic.OBJECT,
        "setState({ ...s,\n  n: s.n + 1 })",
        "Why spread?",
        "React compares by identity",
        "spread is faster",
        "Mutating the old object leaves the reference equal, so nothing rerenders.",
    ),
    q(
        Topic.OBJECT,
        "const o = {\n  toString: () => 'x' }\n`\${o}`",
        "Result?",
        "'x'",
        "'[object Object]'",
        "Template strings call toString, and the default one gives that ugly text.",
    ),
    q(
        Topic.OBJECT,
        "Object.fromEntries(\n  entries)",
        "This does?",
        "turns pairs back into an object",
        "flattens nested objects",
        "It is the inverse of Object.entries, handy after a map or filter.",
    ),
    q(
        Topic.OBJECT,
        "const o = { a: 1, b: 2 }\nJSON.stringify(o)\n  === '{\"a\":1,\"b\":2}'",
        "Reliable for comparing objects?",
        "no, key order can differ",
        "yes, always",
        "Two equal objects can serialise differently. Compare field by field.",
    ),
    q(
        Topic.OBJECT,
        "class P {\n  constructor(\n    private n: number\n  ) {} }",
        "The private does?",
        "declares and assigns the field",
        "only marks it private",
        "A parameter property declares, assigns and marks visibility in one go.",
    ),
    q(
        Topic.OBJECT,
        "class A { #n = 1 }",
        "#n compared to private n?",
        "truly hidden at runtime",
        "the same thing",
        "private is erased after compiling. A hash field is enforced by the engine.",
    ),
    q(
        Topic.OBJECT,
        "const o: Record<\n  string, number> = {}\no.missing.toFixed()",
        "Result?",
        "compiles, crashes at runtime",
        "compile error",
        "An index signature promises a number for every key. It is a comfortable lie.",
    ),
    q(
        Topic.OBJECT,
        "const o =\n  { a: 1 } as const\no.a = 2",
        "Result?",
        "compile error, readonly",
        "fine",
        "as const marks every field readonly all the way down.",
    ),
    q(
        Topic.OBJECT,
        "const m = new Map<\n  string, number>()\nm.get('x')",
        "Type?",
        "number | undefined",
        "number",
        "Map models the miss honestly, unlike a plain object index.",
    ),
)
