package com.abhiram.devquiz

internal val tsTypes: List<Question> = listOf(

    q(
        Topic.TYPES,
        "type A = { n: number }\ninterface B {\n  n: number\n}",
        "Which one can be reopened later?",
        "interface B",
        "type A",
        "Interfaces merge across declarations. A type alias is final.",
    ),
    q(
        Topic.TYPES,
        "type Id =\n  string | number",
        "What is this called?",
        "a union",
        "an intersection",
        "The bar means one or the other. The ampersand means both at once.",
    ),
    q(
        Topic.TYPES,
        "type A =\n  { a: 1 } & { b: 2 }",
        "A value of A has?",
        "both a and b",
        "either a or b",
        "An intersection demands every member of both sides.",
    ),
    q(
        Topic.TYPES,
        "const x = 'go'\nlet y = 'go'",
        "The inferred types?",
        "'go' and string",
        "string and string",
        "const cannot change, so it keeps the literal type. let widens.",
    ),
    q(
        Topic.TYPES,
        "const a =\n  ['x', 'y'] as const",
        "Type of a?",
        "readonly ['x', 'y']",
        "string[]",
        "as const freezes it into a readonly tuple of literals.",
    ),
    q(
        Topic.TYPES,
        "type K =\n  keyof { a: 1; b: 2 }",
        "K is?",
        "'a' | 'b'",
        "1 | 2",
        "keyof gives the key names. Use T[keyof T] for the values.",
    ),
    q(
        Topic.TYPES,
        "type V = T[keyof T]",
        "T[keyof T] gives?",
        "the union of value types",
        "the union of key names",
        "That is an indexed access, so it reads the values out.",
    ),
    q(
        Topic.TYPES,
        "const u: unknown = 1\nconst n: number = u",
        "Does it compile?",
        "no, unknown must be narrowed",
        "yes, unknown is assignable",
        "unknown accepts anything in, but nothing out until you check it.",
    ),
    q(
        Topic.TYPES,
        "const a: any = 1\nconst s: string = a",
        "Does it compile?",
        "yes, any silences the check",
        "no, number is not string",
        "any turns the checker off in both directions. That is why unknown exists.",
    ),
    q(
        Topic.TYPES,
        "function f(): never {}",
        "When does a function return never?",
        "when it always throws or loops",
        "when it returns nothing",
        "Returning nothing is void. never means it never finishes normally.",
    ),
    q(
        Topic.TYPES,
        "type T = string & number",
        "T is?",
        "never",
        "string | number",
        "Nothing can be both, so the intersection collapses to the empty type.",
    ),
    q(
        Topic.TYPES,
        "type P =\n  Partial<{ a: number }>",
        "P is?",
        "{ a?: number }",
        "{ a: number | undefined }",
        "Partial makes every field optional, so the key may be missing entirely.",
    ),
    q(
        Topic.TYPES,
        "type R =\n  Required<{ a?: 1 }>",
        "R is?",
        "{ a: 1 }",
        "{ a?: 1 }",
        "Required strips the question marks that Partial adds.",
    ),
    q(
        Topic.TYPES,
        "type X =\n  Pick<T, 'a' | 'b'>",
        "X keeps?",
        "only a and b",
        "everything but a and b",
        "Pick keeps the listed keys. Omit is the one that removes them.",
    ),
    q(
        Topic.TYPES,
        "type X = Omit<T, 'id'>",
        "X is?",
        "T without id",
        "only T's id",
        "Omit subtracts keys, which is handy for create payloads.",
    ),
    q(
        Topic.TYPES,
        "type M =\n  Record<string, number>",
        "M describes?",
        "any string key, number values",
        "the key 'string' only",
        "Record builds a map type from a key union and a value type.",
    ),
    q(
        Topic.TYPES,
        "type R =\n  ReturnType<typeof f>",
        "R is?",
        "what f returns",
        "f's parameters",
        "Parameters<typeof f> is the one that gives the argument tuple.",
    ),
    q(
        Topic.TYPES,
        "type A = Awaited<\n  Promise<string>>",
        "A is?",
        "string",
        "Promise<string>",
        "Awaited unwraps a promise, and keeps unwrapping nested ones.",
    ),
    q(
        Topic.TYPES,
        "type T = NonNullable<\n  string | null>",
        "T is?",
        "string",
        "string | null",
        "NonNullable strips null and undefined out of a union.",
    ),
    q(
        Topic.TYPES,
        "const c = { a: 1 }\n  satisfies Cfg",
        "satisfies vs a type annotation?",
        "checks it, keeps the narrow type",
        "same as writing : Cfg",
        "An annotation widens the value to Cfg. satisfies validates without widening.",
    ),
    q(
        Topic.TYPES,
        "type F =\n  (n: number) => void",
        "A function returning number?",
        "still assignable to F",
        "rejected, wrong return",
        "A void return position means the caller ignores the result.",
    ),
    q(
        Topic.TYPES,
        "let v: void = undefined",
        "void vs undefined?",
        "void means ignore the result",
        "they are identical",
        "void is about intent at a return position, undefined is a real value.",
    ),
    q(
        Topic.TYPES,
        "type T =\n  [string, number]",
        "T is?",
        "a fixed tuple of two",
        "an array of strings and numbers",
        "A tuple pins both length and the type at each position.",
    ),
    q(
        Topic.TYPES,
        "type T =\n  [string, ...number[]]",
        "Valid?",
        "yes, a rest element",
        "no, tuples are fixed",
        "A tuple can end in a rest element for a head plus tail shape.",
    ),
    q(
        Topic.TYPES,
        "enum E { A, B }",
        "E.A is?",
        "0",
        "'A'",
        "A numeric enum counts from zero. Say A = 'A' for string values.",
    ),
    q(
        Topic.TYPES,
        "const enum E { A }",
        "What is different?",
        "it is inlined, no runtime object",
        "it is readonly at runtime",
        "const enums vanish at compile time, which breaks isolated module builds.",
    ),
    q(
        Topic.TYPES,
        "type S = 'a' | 'b'\nconst x: S = 'c'",
        "Result?",
        "compile error",
        "runtime error only",
        "Literal unions are checked at compile time and erased after that.",
    ),
    q(
        Topic.TYPES,
        "interface P {\n  readonly id: string\n}",
        "readonly stops?",
        "assignment at compile time",
        "mutation at runtime",
        "All type level. Nothing survives into the emitted JavaScript.",
    ),
    q(
        Topic.TYPES,
        "type T = {\n  [k: string]: number\n}",
        "This is?",
        "an index signature",
        "a mapped type",
        "It says any string key maps to a number.",
    ),
    q(
        Topic.TYPES,
        "type M = {\n  [K in keyof T]: string\n}",
        "This is?",
        "a mapped type",
        "an index signature",
        "The in keyword walks existing keys and rewrites their value type.",
    ),
    q(
        Topic.TYPES,
        "type M = {\n  [K in keyof T]?: T[K]\n}",
        "Equivalent to?",
        "Partial<T>",
        "Required<T>",
        "That is literally how Partial is written in the standard library.",
    ),
    q(
        Topic.TYPES,
        "type N = T extends\n  string ? 1 : 0",
        "This is?",
        "a conditional type",
        "a type guard",
        "It is an if statement that runs in the type system.",
    ),
    q(
        Topic.TYPES,
        "type E<T> =\n  T extends (infer U)[]\n  ? U : never",
        "infer U does?",
        "captures the element type",
        "casts T to U",
        "infer names a piece of the matched shape so you can return it.",
    ),
    q(
        Topic.TYPES,
        "type G =\n  `on\${Capitalize<K>}`",
        "This is?",
        "a template literal type",
        "a runtime template string",
        "Template literal types build new string literal unions from old ones.",
    ),
    q(
        Topic.TYPES,
        "function f(\n  p: { a: number }) {}\nf({ a: 1, b: 2 })",
        "Result?",
        "error on the extra b",
        "fine, structural typing",
        "Object literals get an excess property check. A variable would pass.",
    ),
    q(
        Topic.TYPES,
        "const o = { a: 1, b: 2 }\nf(o)",
        "With f(p: { a: number })?",
        "compiles, o has at least a",
        "error, o has an extra key",
        "Structural typing only asks for enough. The extra check is literals only.",
    ),
    q(
        Topic.TYPES,
        "type T = typeof user",
        "typeof in type position?",
        "reads a value's type",
        "returns 'object' at runtime",
        "There are two typeofs. In a type position it lifts a value into a type.",
    ),
    q(
        Topic.TYPES,
        "class C {}\nconst c: C = { }",
        "Does it compile?",
        "yes if the shape matches",
        "no, only new C() works",
        "Classes are structural too, unless they have private members.",
    ),
    q(
        Topic.TYPES,
        "function f(x: string):\n  void\nfunction f(x: number):\n  void",
        "These two lines are?",
        "overload signatures",
        "a duplicate error",
        "Overloads declare call shapes above one real implementation.",
    ),
    q(
        Topic.TYPES,
        "type A = string[]\ntype B = Array<string>",
        "Difference?",
        "none, same type",
        "B is mutable, A is not",
        "Pure syntax. Pick one and stay consistent.",
    ),
    q(
        Topic.TYPES,
        "let a: readonly\n  number[] = [1]\na.push(2)",
        "Result?",
        "compile error",
        "fine",
        "readonly arrays drop the mutating methods from the type.",
    ),
    q(
        Topic.TYPES,
        "type T = { a?: number }",
        "a's type inside?",
        "number | undefined",
        "number",
        "Optional adds undefined, and lets the key be absent as well.",
    ),
    q(
        Topic.TYPES,
        "const x = obj!.a",
        "The ! does?",
        "asserts not null, no runtime check",
        "throws if obj is null",
        "It only silences the checker. If you are wrong you get a runtime crash.",
    ),
    q(
        Topic.TYPES,
        "const el =\n  x as HTMLInputElement",
        "as does?",
        "reinterprets the type only",
        "converts the value",
        "There is no runtime cast in TypeScript. Wrong assertions crash later.",
    ),
    q(
        Topic.TYPES,
        "type T = Parameters<\n  typeof f>[0]",
        "T is?",
        "the type of f's first argument",
        "f's return type",
        "Parameters gives a tuple, so index it to pick one argument.",
    ),
    q(
        Topic.TYPES,
        "type Fn = {\n  (n: number): void\n  calls: number\n}",
        "This describes?",
        "a callable with a property",
        "an illegal type",
        "A call signature plus fields is how you type a function that carries state.",
    ),
)

internal val tsNarrow: List<Question> = listOf(

    q(
        Topic.NARROW,
        "// x: string | number\nif (typeof x ===\n  'string')",
        "Inside the if, x is?",
        "string",
        "still string | number",
        "A typeof check narrows the union for the rest of that block.",
    ),
    q(
        Topic.NARROW,
        "if (Array.isArray(x))",
        "Why does this narrow?",
        "it is a type predicate",
        "arrays are special cased",
        "isArray is declared as x is any[], so the checker follows it.",
    ),
    q(
        Topic.NARROW,
        "function isCat(a: A):\n  a is Cat",
        "The return type does?",
        "narrows a at the call site",
        "just documents the intent",
        "A predicate return teaches the checker what a true result means.",
    ),
    q(
        Topic.NARROW,
        "type S =\n  | {k:'a'; n:number}\n  | {k:'b'; s:string}",
        "Switching on k gives?",
        "the matching branch's fields",
        "all fields as optional",
        "That shared literal field is the discriminant. It is the cleanest narrowing.",
    ),
    q(
        Topic.NARROW,
        "if ('wheels' in v)",
        "Result?",
        "narrows to the member with wheels",
        "a runtime only check",
        "The in operator narrows a union by which keys exist.",
    ),
    q(
        Topic.NARROW,
        "if (x) { ... }\n// x: string | undefined",
        "Inside, x is?",
        "string",
        "string | undefined",
        "A truthiness check removes undefined, and it removes '' too.",
    ),
    q(
        Topic.NARROW,
        "// x: number | undefined\nif (x) {}",
        "Which live case does this drop?",
        "x === 0",
        "none, it is safe",
        "0 is falsy, so a real zero skips the block. Test x !== undefined.",
    ),
    q(
        Topic.NARROW,
        "// x: string | null\n//    | undefined\nif (x !== null) {}",
        "Inside, x is?",
        "string | undefined",
        "string",
        "!== null removes exactly null. Use != null to drop both.",
    ),
    q(
        Topic.NARROW,
        "if (x != null) {}",
        "This removes?",
        "null and undefined",
        "null only",
        "Loose != null is the one idiomatic use of the loose operator.",
    ),
    q(
        Topic.NARROW,
        "const v =\n  e instanceof Error\n  ? e.message\n  : String(e)",
        "Why the check?",
        "catch gives unknown",
        "Error is not a class",
        "Anything can be thrown, so a caught value is unknown until proven.",
    ),
    q(
        Topic.NARROW,
        "if (o.a && o.a.b) {}",
        "Shorter form?",
        "if (o.a?.b)",
        "if (o.a!.b)",
        "Optional chaining does the same guard without repeating the path.",
    ),
    q(
        Topic.NARROW,
        "// s: 'a' | 'b'\nswitch (s) {\n  case 'a': ...\n}",
        "In default, s is?",
        "'b'",
        "'a' | 'b'",
        "Each handled case is subtracted, so the default holds the leftovers.",
    ),
    q(
        Topic.NARROW,
        "default:\n  const _: never = s",
        "What does this catch?",
        "a new union member you forgot",
        "a runtime bad value",
        "Exhaustiveness check. Add a case and the assignment stops compiling.",
    ),
    q(
        Topic.NARROW,
        "// o: { a?: string }\nif (o.a) {}\nsetTimeout(() =>\n  o.a.length)",
        "Inside the callback?",
        "narrowing is lost",
        "still narrowed",
        "A later call could change o.a, so narrowing does not survive a closure.",
    ),
    q(
        Topic.NARROW,
        "const a = o.a\nif (a) { a.length }",
        "Why copy to a const?",
        "narrowing sticks on a const",
        "it is faster",
        "The checker knows a const cannot change, so the narrowing holds.",
    ),
    q(
        Topic.NARROW,
        "// arr: string[]\nconst first = arr[0]",
        "first's type?",
        "string, even if empty",
        "string | undefined",
        "Index access lies by default. noUncheckedIndexedAccess fixes it.",
    ),
    q(
        Topic.NARROW,
        "const found =\n  arr.find(fn)",
        "found's type?",
        "T | undefined",
        "T",
        "find models the miss. Index access does not, which is the trap above.",
    ),
    q(
        Topic.NARROW,
        "const n =\n  arr.filter(Boolean)",
        "Does it drop null from the type?",
        "no, without a predicate",
        "yes, automatically",
        "Use filter((x): x is T => x != null) to narrow the result type.",
    ),
    q(
        Topic.NARROW,
        "// x: object | null\nif (typeof x ===\n  'object') {}",
        "x may still be?",
        "null",
        "undefined",
        "typeof null is 'object', so this famous check lets null through.",
    ),
    q(
        Topic.NARROW,
        "try {} catch (e) {}",
        "e's type today?",
        "unknown",
        "Error",
        "It was any before TypeScript 4.4, and useUnknownInCatchVariables.",
    ),
)
