package com.abhiram.devquiz

internal val tsGeneric: List<Question> = listOf(

    q(
        Topic.GENERIC,
        "function id<T>(x: T): T",
        "Calling id(1) gives?",
        "1, typed as number",
        "1, typed as unknown",
        "T is inferred from the argument at each call site.",
    ),
    q(
        Topic.GENERIC,
        "function f<T>(x: T[]): T",
        "Why not any[]?",
        "T ties input to output",
        "no real difference",
        "A generic remembers the element type. any throws it away.",
    ),
    q(
        Topic.GENERIC,
        "function k<T,\n  K extends keyof T>(\n  o: T, k: K): T[K]",
        "This gives back?",
        "the exact type of that field",
        "the union of all field types",
        "Constraining K to keyof T is what makes a typed get helper work.",
    ),
    q(
        Topic.GENERIC,
        "function f<T extends\n  { id: string }>",
        "The extends clause does?",
        "requires T to have id",
        "makes T a subclass",
        "In generics extends means 'at least this shape', not inheritance.",
    ),
    q(
        Topic.GENERIC,
        "function f<T = string>()",
        "The = string is?",
        "a default type argument",
        "a runtime default",
        "It applies when the call site gives nothing to infer from.",
    ),
    q(
        Topic.GENERIC,
        "const first =\n  <T,>(a: T[]) => a[0]",
        "Why the comma in a .tsx file?",
        "so it is not read as JSX",
        "it is a typo",
        "In TSX a bare <T> looks like a tag. The comma or extends fixes it.",
    ),
    q(
        Topic.GENERIC,
        "type B<T> = T extends\n  string ? 'yes' : 'no'\ntype R =\n  B<string | number>",
        "R is?",
        "'yes' | 'no'",
        "'no'",
        "A naked type parameter distributes the condition over the union.",
    ),
    q(
        Topic.GENERIC,
        "type B<T> =\n  [T] extends [string]\n  ? 1 : 0",
        "The brackets do?",
        "stop the union distributing",
        "make it an array check",
        "Wrapping in a tuple is the standard way to switch distribution off.",
    ),
    q(
        Topic.GENERIC,
        "useState<\n  string | null>(null)",
        "Why pass the type?",
        "null alone infers null only",
        "useState needs it always",
        "Without it the state type is null and you cannot set a string later.",
    ),
    q(
        Topic.GENERIC,
        "class Box<T> {\n  constructor(\n    public v: T) {}\n}",
        "new Box('a').v is?",
        "string",
        "unknown",
        "Class generics infer from constructor arguments the same way.",
    ),
    q(
        Topic.GENERIC,
        "function f<T>(x: T) {\n  x.length\n}",
        "Result?",
        "error, T is unconstrained",
        "fine, everything has length",
        "An unconstrained T could be anything. Constrain it to { length: number }.",
    ),
    q(
        Topic.GENERIC,
        "type A<T> =\n  T extends any[]\n  ? T[number] : T",
        "T[number] means?",
        "the element type",
        "the length",
        "Indexing an array type by number gives you what is inside.",
    ),
    q(
        Topic.GENERIC,
        "function pick<T,\n  K extends keyof T>(\n  o: T, ks: K[]\n): Pick<T, K>",
        "Passing a bad key gives?",
        "a compile error",
        "undefined at runtime",
        "K is pinned to the real keys, so typos never reach runtime.",
    ),
    q(
        Topic.GENERIC,
        "type DP<T> = {\n  [K in keyof T]?:\n    DP<T[K]>\n}",
        "This is?",
        "a recursive mapped type",
        "illegal, no recursion",
        "Type aliases may reference themselves through object members.",
    ),
    q(
        Topic.GENERIC,
        "function f(\n  cb: <T>(x: T) => T)",
        "Where does T bind?",
        "at each call of cb",
        "when f is called",
        "The parameter list holding it decides. Here it stays generic inside cb.",
    ),
)

internal val tsAsync: List<Question> = listOf(

    q(
        Topic.ASYNC,
        "async function f() {\n  return 1 }\nconst x = f()",
        "x is?",
        "a Promise<number>",
        "1",
        "async always wraps the result. You have to await it to see the value.",
    ),
    q(
        Topic.ASYNC,
        "log(1)\nsetTimeout(() => log(2))\nPromise.resolve()\n  .then(() => log(3))",
        "Order?",
        "1 3 2",
        "1 2 3",
        "Microtasks like then run before any timer, however short.",
    ),
    q(
        Topic.ASYNC,
        "for (const u of urls) {\n  await fetch(u)\n}",
        "This runs?",
        "one at a time",
        "all in parallel",
        "await inside a loop serialises. Build the promises first, then Promise.all.",
    ),
    q(
        Topic.ASYNC,
        "await Promise.all(\n  urls.map(fetch))",
        "One rejects. Result?",
        "the whole thing rejects at once",
        "you get the successful ones",
        "all is fail fast. allSettled is the one that reports each outcome.",
    ),
    q(
        Topic.ASYNC,
        "await Promise\n  .allSettled(ps)",
        "Each item is?",
        "{ status, value or reason }",
        "the resolved value",
        "You unwrap by checking status === 'fulfilled'.",
    ),
    q(
        Topic.ASYNC,
        "Promise.race([a, b])",
        "It settles when?",
        "the first one settles, ok or not",
        "the first one succeeds",
        "any is the one that waits for the first success.",
    ),
    q(
        Topic.ASYNC,
        "arr.forEach(async x => {\n  await save(x)\n})\nlog('done')",
        "When does it log?",
        "before any save finishes",
        "after all saves",
        "forEach ignores the returned promises. Use a for..of loop or Promise.all.",
    ),
    q(
        Topic.ASYNC,
        "const r = arr.map(\n  async x => x * 2)",
        "r is?",
        "an array of promises",
        "an array of numbers",
        "map does not await. Wrap it in await Promise.all.",
    ),
    q(
        Topic.ASYNC,
        "try { doAsync() }\ncatch (e) {}",
        "Does it catch the rejection?",
        "no, the await is missing",
        "yes",
        "Without await the promise escapes the try block entirely.",
    ),
    q(
        Topic.ASYNC,
        "const p = fetch(u)\nawait sleep(1000)\nawait p",
        "When did the request start?",
        "immediately, at fetch",
        "at the await",
        "Promises are eager. Calling the function already started the work.",
    ),
    q(
        Topic.ASYNC,
        "await Promise.resolve(1)",
        "Awaiting a non promise?",
        "works, resolves next microtask",
        "throws",
        "await accepts any value, so generic code does not have to check.",
    ),
    q(
        Topic.ASYNC,
        "async function f() {\n  throw 1 }",
        "f() does?",
        "returns a rejected promise",
        "throws synchronously",
        "Errors inside async become rejections, never synchronous throws.",
    ),
    q(
        Topic.ASYNC,
        "const res =\n  await fetch(url)\nif (res.ok)",
        "A 404 does what to fetch?",
        "resolves, ok is false",
        "rejects",
        "fetch only rejects on network failure. You must check status yourself.",
    ),
    q(
        Topic.ASYNC,
        "const data =\n  await res.json()",
        "Type of data?",
        "any",
        "unknown",
        "json() returns any, which quietly disables checking. Validate or cast it.",
    ),
    q(
        Topic.ASYNC,
        "return await p",
        "Inside a try, dropping await?",
        "loses the catch block",
        "changes nothing",
        "Return without await hands the rejection to the caller, past your catch.",
    ),
    q(
        Topic.ASYNC,
        "new Promise(res => {\n  res(1); res(2)\n})",
        "It resolves to?",
        "1",
        "2",
        "A promise settles once. Later calls are ignored, not an error.",
    ),
    q(
        Topic.ASYNC,
        "p.then(f).catch(g)\np.catch(g).then(f)",
        "Difference?",
        "the second runs f after a caught error",
        "none",
        "Order matters. catch first means the chain continues as fulfilled.",
    ),
    q(
        Topic.ASYNC,
        "const c =\n  new AbortController()\nfetch(u,\n  { signal: c.signal })",
        "c.abort() causes?",
        "the fetch to reject",
        "the fetch to resolve empty",
        "You get an AbortError, which you usually ignore rather than report.",
    ),
    q(
        Topic.ASYNC,
        "await Promise.all(\n  [a(), b()])",
        "vs awaiting each in turn?",
        "runs both at once",
        "identical timing",
        "Two sequential awaits add their times. Promise.all overlaps them.",
    ),
    q(
        Topic.ASYNC,
        "queueMicrotask\nvs setTimeout(f, 0)",
        "Which runs first?",
        "queueMicrotask",
        "setTimeout",
        "The microtask queue drains fully before the next macrotask.",
    ),
    q(
        Topic.ASYNC,
        "for await (\n  const c of stream)",
        "This needs?",
        "an async iterable",
        "an array of promises",
        "It pulls one value at a time, awaiting each. Great for streams.",
    ),
    q(
        Topic.ASYNC,
        "const [a, b] =\n  await Promise.all([\n    fa(), fb()])",
        "Types of a and b?",
        "kept separate per position",
        "a union of both",
        "Promise.all is typed over the tuple, so each slot keeps its own type.",
    ),
)
