package com.abhiram.devquiz

import androidx.compose.ui.graphics.Color

enum class Topic(val label: String, val color: Color) {
    RENDER("RENDER", Color(0xFF61DAFB)),
    STATE("STATE", Color(0xFFA78BFA)),
    PERF("PERF", Color(0xFFFBBF24)),
    TYPES("TYPES", Color(0xFF60A5FA)),
    RUNTIME("RUNTIME", Color(0xFFF472B6)),
    DESIGN("DESIGN", Color(0xFF4ADE80)),
    DEBUG("DEBUG", Color(0xFFFB923C)),
    CODE("CODE", Color(0xFF2DD4BF)),
}

class Question(
    val topic: Topic,
    val prompt: String,
    val correct: String,
    val wrong: String,
    val why: String,
) {
    val id: Int = prompt.hashCode()
}

private fun q(topic: Topic, prompt: String, correct: String, wrong: String, why: String) =
    Question(topic, prompt, correct, wrong, why)

object Questions {

    val all: List<Question> = listOf(

        q(
            Topic.RENDER,
            "You call setCount, then read count on the next line. What do you get?",
            "the old value",
            "the new value",
            "State is a snapshot. The new value only shows up on the next render.",
        ),
        q(
            Topic.RENDER,
            "setN(n + 1) twice in one handler. How far does n move?",
            "by 1",
            "by 2",
            "Both lines read the same n. Use setN(c => c + 1) to stack them.",
        ),
        q(
            Topic.RENDER,
            "Which phase can React throw away and start over?",
            "render",
            "commit",
            "Render can be interrupted, so it has to be pure. Commit runs once, start to finish.",
        ),
        q(
            Topic.RENDER,
            "What breaks when you key a reorderable list by index?",
            "state sticks to the row, not the item",
            "you get a duplicate key warning",
            "React reuses the old row for a new item, and the state comes along with it.",
        ),
        q(
            Topic.RENDER,
            "Keys have to be unique where?",
            "among siblings",
            "across the whole app",
            "React only ever compares children inside the same parent.",
        ),
        q(
            Topic.RENDER,
            "When does React throw a component away and build a new one?",
            "when the key or the type changes",
            "when any prop changes",
            "Same type and same key means React keeps it and just updates the props.",
        ),
        q(
            Topic.RENDER,
            "How do you remount a child without touching the parent?",
            "give it a new key",
            "call forceUpdate",
            "A new key makes React treat it as a different component, so its state resets.",
        ),
        q(
            Topic.RENDER,
            "The deps changed. What runs first?",
            "the old cleanup",
            "the new effect",
            "React always tears the old one down before setting the new one up.",
        ),
        q(
            Topic.RENDER,
            "When does useLayoutEffect run?",
            "after the DOM changes, before you see it",
            "before React touches the DOM",
            "That gap is where you can measure and fix layout with no flicker.",
        ),
        q(
            Topic.RENDER,
            "What does useLayoutEffect cost you?",
            "it holds up the paint",
            "it skips batching",
            "Slow work in there freezes the frame, and the user sees it.",
        ),
        q(
            Topic.RENDER,
            "Why does StrictMode run effects twice in dev?",
            "to catch effects with no cleanup",
            "to find slow components",
            "Running setup twice breaks anything that forgot to clean up. That is the bug.",
        ),
        q(
            Topic.RENDER,
            "What is tearing?",
            "one render showing two different values",
            "a component unmounting mid animation",
            "Render can pause, and an outside store can change while it is paused.",
        ),
        q(
            Topic.RENDER,
            "Why does useSyncExternalStore exist?",
            "React cannot see changes in outside stores",
            "subscriptions were too slow",
            "It gives React a way to notice the change instead of rendering half old data.",
        ),
        q(
            Topic.RENDER,
            "setInterval in an effect with no deps. Which state does it see?",
            "whatever it was on the first render",
            "the latest",
            "That callback kept the first render variables. Nothing ever hands it new ones.",
        ),
        q(
            Topic.RENDER,
            "How do you fix a stale interval without restarting it every tick?",
            "use setC(c => c + 1)",
            "add the value to the deps",
            "The updater asks React for the current value, so the effect never has to rerun.",
        ),
        q(
            Topic.RENDER,
            "Stale closure, but you need the whole latest function. What works?",
            "keep it in a ref",
            "wrap it in useCallback",
            "useCallback still hands you a function from one render. A ref is a box you update.",
        ),
        q(
            Topic.RENDER,
            "Why does render have to be pure?",
            "React may run it twice and bin one",
            "React caches the JSX",
            "Side effects in render happen an unpredictable number of times.",
        ),
        q(
            Topic.RENDER,
            "What does React.memo compare?",
            "props, one level deep",
            "what the component rendered",
            "A new object or an inline function looks different every time, so memo never helps.",
        ),
        q(
            Topic.RENDER,
            "When is useMemo a waste?",
            "when comparing costs more than the work",
            "when the deps list is long",
            "You pay for a check and held memory just to skip an addition.",
        ),
        q(
            Topic.RENDER,
            "useCallback on a prop, but the child is not memoized. What happens?",
            "nothing, you just pay for it",
            "the child still skips its rerender",
            "The child rerenders with the parent anyway. A stable identity only matters to memo.",
        ),
        q(
            Topic.RENDER,
            "Where should a derived value be worked out?",
            "during render",
            "in an effect that sets state",
            "An effect means a second render and a moment where the screen is wrong.",
        ),
        q(
            Topic.RENDER,
            "What does React 18 batch?",
            "updates anywhere, promises and timeouts too",
            "only updates in event handlers",
            "React 17 stopped at the event system. 18 does not.",
        ),
        q(
            Topic.RENDER,
            "Where does a component actually keep its state?",
            "on the fiber for that spot in the tree",
            "in a map keyed by the component name",
            "That is why the same component in two places has two separate states.",
        ),
        q(
            Topic.RENDER,
            "Why can a hook not go inside an if?",
            "React matches hooks by order",
            "React reads your variable names",
            "Skipping one shifts every hook after it onto the wrong slot.",
        ),
        q(
            Topic.RENDER,
            "A context value changes. Who rerenders?",
            "everyone reading it",
            "only the ones whose props changed",
            "Context is all or nothing. A memo in between does not stop it.",
        ),
        q(
            Topic.RENDER,
            "How does React decide whether to reuse a child?",
            "by type and key at the same spot",
            "by diffing the whole subtree",
            "It is one quick pass, which is exactly why keys matter so much.",
        ),
        q(
            Topic.RENDER,
            "What makes Suspense show a fallback?",
            "a child throws a promise while rendering",
            "a child returns null",
            "The thrown promise is the signal. The boundary tries again when it resolves.",
        ),
        q(
            Topic.RENDER,
            "Why is reading a ref during render unsafe?",
            "it can change between two goes at the same render",
            "refs are null during render",
            "You can end up showing two different values from the same source.",
        ),

        q(
            Topic.STATE,
            "How do you know something is server state?",
            "the server owns it and it can go stale",
            "it came from a fetch",
            "Who owns the truth picks the tool. Stale truth needs caching, not a reducer.",
        ),
        q(
            Topic.STATE,
            "What belongs in the URL?",
            "anything worth sharing or reloading into",
            "nothing, URLs are for routes",
            "Put the filters and the tab there and back, reload and share all work for free.",
        ),
        q(
            Topic.STATE,
            "What does stale while revalidate do?",
            "shows the cached value, then refetches",
            "waits for fresh data",
            "Instant screen now, correct screen a moment later.",
        ),
        q(
            Topic.STATE,
            "After a mutation, what do you do to the related queries?",
            "mark them stale",
            "clear the cache",
            "Stale means they refetch when someone is looking. Clearing causes a spinner storm.",
        ),
        q(
            Topic.STATE,
            "What does an optimistic update need in order to undo itself?",
            "a copy of the value from before",
            "a retry",
            "You cannot put back what you never saved.",
        ),
        q(
            Topic.STATE,
            "Two optimistic updates on the same item. What goes wrong?",
            "undoing one wipes out the other",
            "nothing, they cannot clash",
            "The second copy you saved already had the first change in it.",
        ),
        q(
            Topic.STATE,
            "Why is context bad for a value that changes constantly?",
            "you cannot subscribe to just part of it",
            "context is not memoized",
            "Everyone reading it rerenders, every single time.",
        ),
        q(
            Topic.STATE,
            "Context is rerendering everything. Best fix?",
            "split the stable parts from the changing parts",
            "wrap the readers in memo",
            "memo cannot block context. Splitting the provider actually cuts the work.",
        ),
        q(
            Topic.STATE,
            "Search as you type. What is the race?",
            "an old reply lands after a new one",
            "replies always come back in order",
            "The stale result arrives last and wins.",
        ),
        q(
            Topic.STATE,
            "How do you stop an old reply overwriting a new one?",
            "ignore anything that is not the latest request",
            "make the debounce longer",
            "Debouncing makes it rarer. It does not make it impossible.",
        ),
        q(
            Topic.STATE,
            "Typeahead. Debounce or throttle?",
            "debounce",
            "throttle",
            "Only the last thing they typed matters, so wait for them to stop.",
        ),
        q(
            Topic.STATE,
            "What is a request waterfall?",
            "a fetch that waits for its parent to finish",
            "too many requests at once",
            "The delays stack up one after another instead of overlapping.",
        ),
        q(
            Topic.STATE,
            "How do you flatten a waterfall?",
            "start the fetches together, higher up",
            "add a spinner at each level",
            "Move the data needs up to the route so nothing has to wait its turn.",
        ),
        q(
            Topic.STATE,
            "What forces a component to be a client component?",
            "state, effects, refs or event handlers",
            "importing any package",
            "It is about interactivity and browser APIs, not where the code came from.",
        ),
        q(
            Topic.STATE,
            "Five requests fail with 401 at once. What should happen?",
            "one refresh that all five wait on",
            "each one refreshes on its own",
            "Five refreshes race, and four of them kill the token the first one just got.",
        ),
        q(
            Topic.STATE,
            "Where does token refresh belong?",
            "in one place that queues the failures",
            "in each component that fetches",
            "Only one central spot can share the refresh and replay what failed.",
        ),
        q(
            Topic.STATE,
            "Before adding a state library, what do you try?",
            "lifting the state up",
            "nothing, the library scales better",
            "The simple option costs nothing to undo. A library is yours forever.",
        ),
        q(
            Topic.STATE,
            "Why normalize cached data?",
            "one update fixes it everywhere it shows",
            "a smaller bundle",
            "Copies of the same record drift apart and you end up patching four caches.",
        ),
        q(
            Topic.STATE,
            "Why refetch when the window gets focus again?",
            "they were away and things may have moved",
            "to keep the connection alive",
            "It is the cheapest way to feel live without opening a socket.",
        ),
        q(
            Topic.STATE,
            "Where should form state usually live?",
            "in the field, until submit",
            "in global state",
            "Global form state means every keystroke rerenders everything watching it.",
        ),
        q(
            Topic.STATE,
            "A mutation invalidates a list nobody is looking at. Then what?",
            "it refetches when someone opens it",
            "it refetches straight away",
            "No point fetching a screen nobody is on.",
        ),
        q(
            Topic.STATE,
            "What is a query key for?",
            "sharing one request and one cache entry",
            "labelling it in devtools",
            "Two components asking with the same key get one fetch, not two.",
        ),

        q(
            Topic.PERF,
            "The page feels slow. What do you do first?",
            "measure, and find the long tasks",
            "memoize the big components",
            "Guessing usually adds code that changes nothing.",
        ),
        q(
            Topic.PERF,
            "How do you tell one slow render from lots of small ones?",
            "one wide bar versus many thin bars",
            "you cannot tell them apart",
            "The shape of the flame chart picks the fix for you.",
        ),
        q(
            Topic.PERF,
            "Too many rerenders. What do you change?",
            "what is triggering them",
            "how fast each one is",
            "Split the state, narrow the context, stop passing new objects.",
        ),
        q(
            Topic.PERF,
            "One render is slow. What do you change?",
            "how much work it does",
            "wrap the parent in memo",
            "Draw fewer rows, move the heavy bit out, or get it off the main thread.",
        ),
        q(
            Topic.PERF,
            "What does a big bundle mostly cost you?",
            "the wait before the page responds",
            "how fast it renders later",
            "Reading and running the JS blocks everything until it is done.",
        ),
        q(
            Topic.PERF,
            "What does INP measure?",
            "how fast the screen reacts to a tap",
            "how fast the server replies",
            "It is about how the app feels under your finger.",
        ),
        q(
            Topic.PERF,
            "Why is INP the hard one in a single page app?",
            "long tasks make taps wait",
            "images are slow",
            "Anything over 50ms is a queue the tap has to sit behind.",
        ),
        q(
            Topic.PERF,
            "Virtualizing rows of different heights needs what?",
            "real measured heights, remembered",
            "one good estimate",
            "Guesses make the scrollbar and the positions jump once the real heights land.",
        ),
        q(
            Topic.PERF,
            "What does virtualization quietly break?",
            "find in page",
            "nothing, it is invisible",
            "Rows off screen are not in the page, so search and screen readers miss them.",
        ),
        q(
            Topic.PERF,
            "You build the context value inline. What happens?",
            "everyone rerenders every time",
            "only the provider rerenders",
            "It is a new object each render, so context tells everyone something changed.",
        ),
        q(
            Topic.PERF,
            "How do you avoid a chain of spinners?",
            "fewer boundaries, higher up, and prefetch",
            "make each spinner shorter",
            "Lots of small boundaries means lots of things popping in one after another.",
        ),
        q(
            Topic.PERF,
            "Where do you split a dashboard bundle?",
            "per route, then per heavy widget",
            "per file",
            "Splitting everything trades one download for a hundred.",
        ),
        q(
            Topic.PERF,
            "What does useDeferredValue do?",
            "keeps typing fast while the list catches up",
            "waits a set number of ms",
            "It works on priority, not a timer, so it adapts to how slow things really are.",
        ),
        q(
            Topic.PERF,
            "useTransition or useDeferredValue?",
            "transition for an update you make, deferred for a value you get",
            "same thing",
            "Pick by whether you own the setState or only see the prop.",
        ),
        q(
            Topic.PERF,
            "Filtering 50k rows on every keystroke. What is true?",
            "it blocks the screen, get it off the main thread",
            "useMemo fixes it",
            "useMemo skips repeat work. The one pass you do need still freezes everything.",
        ),
        q(
            Topic.PERF,
            "What can a web worker not do?",
            "touch the page",
            "call fetch",
            "There is no DOM in there, and anything you send it gets copied.",
        ),
        q(
            Topic.PERF,
            "What causes layout shift?",
            "things appearing or resizing with no space saved",
            "slow JavaScript",
            "Reserve the size for images, banners and anything that loads late.",
        ),
        q(
            Topic.PERF,
            "What is usually the biggest performance win?",
            "less JavaScript and fewer elements",
            "more memoizing",
            "Memoizing patches one spot. Sheer volume is what costs you frames.",
        ),
        q(
            Topic.PERF,
            "What does the React Profiler tell you?",
            "what rendered, and why",
            "which requests were slow",
            "Profiler for render cost, Performance panel for long tasks.",
        ),
        q(
            Topic.PERF,
            "Why does an inline object prop break memo?",
            "it is a new object every render",
            "memo ignores objects",
            "Same contents, different object, so the check fails.",
        ),

        q(
            Topic.TYPES,
            "What can interface do that type cannot?",
            "be added to later",
            "extend something else",
            "Merging is the real difference. Both of them can extend.",
        ),
        q(
            Topic.TYPES,
            "When does declaration merging actually matter?",
            "when adding to a type you do not own",
            "when you want less code",
            "It is for patching a library type or a global.",
        ),
        q(
            Topic.TYPES,
            "unknown or any?",
            "unknown makes you check first",
            "no real difference",
            "any turns the checker off and spreads. unknown makes you prove what it is.",
        ),
        q(
            Topic.TYPES,
            "What does never mean?",
            "a value that cannot happen",
            "null or undefined",
            "It marks code that can never run, which is what makes exhaustive checks work.",
        ),
        q(
            Topic.TYPES,
            "Where does never turn up by accident?",
            "when narrowing leaves nothing",
            "when you skip a return type",
            "Also from an empty array literal, which then rejects everything you push.",
        ),
        q(
            Topic.TYPES,
            "Why can you pass a callback that takes fewer arguments?",
            "extra arguments are just ignored",
            "it is a hole in the type system",
            "It is the reason arr.map(x => x) works at all.",
        ),
        q(
            Topic.TYPES,
            "How are method parameters checked?",
            "loosely, in both directions",
            "strictly, like function properties",
            "Methods stayed loose for compatibility, so strictFunctionTypes skips them.",
        ),
        q(
            Topic.TYPES,
            "One of two props, never both. How?",
            "a union of two shapes",
            "make both optional and check at runtime",
            "Two optional props let the impossible combination compile just fine.",
        ),
        q(
            Topic.TYPES,
            "How do you force a switch to handle every case?",
            "assign to never in the default branch",
            "add a lint rule",
            "Add a new case and every switch that forgot it stops compiling.",
        ),
        q(
            Topic.TYPES,
            "Why is DeepPartial risky?",
            "it hides data that is genuinely missing",
            "it only slows the compiler",
            "Everything goes optional, so nothing asks whether you built a real object.",
        ),
        q(
            Topic.TYPES,
            "What is infer for?",
            "pulling a type out of another type",
            "giving a generic a default",
            "It is how ReturnType and Awaited are built.",
        ),
        q(
            Topic.TYPES,
            "ReturnType of an async function gives you what?",
            "a Promise",
            "the value inside it",
            "async always wraps it. Awaited is what unwraps it.",
        ),
        q(
            Topic.TYPES,
            "Why constrain a generic instead of just naming the type?",
            "you read the field and keep the caller exact type",
            "there is no difference",
            "Naming the type throws away everything else the caller passed in.",
        ),
        q(
            Topic.TYPES,
            "What does an as prop need to stay type safe?",
            "a generic, plus that element own props",
            "props typed as any",
            "That is what keeps href checked when as is a link.",
        ),
        q(
            Topic.TYPES,
            "What is a branded type?",
            "a normal type with an invisible marker",
            "a class wrapper",
            "Costs nothing at runtime and stops two ids being swapped.",
        ),
        q(
            Topic.TYPES,
            "Why brand a UserId?",
            "so an OrderId cannot be passed instead",
            "so it is shorter to write",
            "To TypeScript they are both just strings until you brand them.",
        ),
        q(
            Topic.TYPES,
            "How does TypeScript decide if two types match?",
            "by their shape",
            "by their name",
            "Anything with the right fields fits, whether it said so or not.",
        ),
        q(
            Topic.TYPES,
            "What does satisfies give you?",
            "the check, without widening the value",
            "a runtime check",
            "A plain annotation would flatten your exact keys into the general type.",
        ),
        q(
            Topic.TYPES,
            "Why is casting a fetch response a lie?",
            "nothing checks the actual data",
            "casts are slow",
            "The crash lands far away, wherever someone reads the field that was missing.",
        ),
        q(
            Topic.TYPES,
            "Where should you check incoming data?",
            "once, at the edge",
            "in every component that reads it",
            "Parse it once and the rest of the app can trust the types again.",
        ),
        q(
            Topic.TYPES,
            "When do you stop writing clever types?",
            "when the type is harder than the bug",
            "never, more types is better",
            "Build time and the next person reading it are both real costs.",
        ),
        q(
            Topic.TYPES,
            "Reading a Record key that is not there gives you what?",
            "the value type, as if it were there",
            "possibly undefined",
            "That default is where cannot read property of undefined comes from.",
        ),
        q(
            Topic.TYPES,
            "What does readonly actually do?",
            "nothing at runtime",
            "freezes the object",
            "It is a compile time promise. Use Object.freeze if you need it enforced.",
        ),
        q(
            Topic.TYPES,
            "Why write import type?",
            "so the import disappears from the output",
            "for better inference",
            "It stops accidental cycles and side effects at runtime.",
        ),
        q(
            Topic.TYPES,
            "Why is any worse than a cast?",
            "it spreads to everything it touches",
            "it stays where you put it",
            "Everything downstream quietly stops being checked.",
        ),
        q(
            Topic.TYPES,
            "When do you actually need overloads?",
            "when the return type depends on the arguments",
            "for documentation",
            "A union parameter cannot say which input gives which output.",
        ),
        q(
            Topic.TYPES,
            "How much does TypeScript check a type predicate?",
            "not at all, it takes your word",
            "fully",
            "A wrong one is a silent lie, so keep the body obvious.",
        ),
        q(
            Topic.TYPES,
            "When does TypeScript complain about extra properties?",
            "only on an object written inline",
            "on every assignment",
            "Put it in a variable first and the extra key sails straight through.",
        ),

        q(
            Topic.RUNTIME,
            "Between two timers, how many microtasks run?",
            "all of them",
            "one",
            "The whole queue drains, which is how promises can starve the screen.",
        ),
        q(
            Topic.RUNTIME,
            "setTimeout with 0, or a resolved promise. Which runs first?",
            "the promise",
            "the timeout",
            "Microtasks all run before the next timer is even looked at.",
        ),
        q(
            Topic.RUNTIME,
            "What does await actually do?",
            "books the rest of the function for later",
            "blocks the thread",
            "Nothing blocks. The function pauses and the stack unwinds.",
        ),
        q(
            Topic.RUNTIME,
            "When does Promise.all reject?",
            "the moment one of them fails",
            "after all of them finish",
            "The others keep running, and their failures become unhandled rejections.",
        ),
        q(
            Topic.RUNTIME,
            "When do you actually need allSettled?",
            "when some of them failing is still useful",
            "when you want the fastest one",
            "Batch work where three out of five succeeding still counts.",
        ),
        q(
            Topic.RUNTIME,
            "race or any?",
            "race takes the first to finish, any the first to work",
            "same thing",
            "race reports an early failure. any waits until they have all failed.",
        ),
        q(
            Topic.RUNTIME,
            "How do you keep exactly N requests running at once?",
            "N workers pulling from one list",
            "await batches of N",
            "Batches wait for the slowest one before the next batch starts.",
        ),
        q(
            Topic.RUNTIME,
            "How does an AbortController reach nested calls?",
            "you pass the signal to each one",
            "it cancels everything automatically",
            "There is no magic here. You thread it through by hand.",
        ),
        q(
            Topic.RUNTIME,
            "What happens when you abort a fetch?",
            "it rejects with an AbortError",
            "it resolves with nothing",
            "Expect it and ignore it. It is not a real failure.",
        ),
        q(
            Topic.RUNTIME,
            "What leaks most often in a long running app?",
            "something subscribed and never unsubscribed",
            "too many components",
            "Listeners, intervals and sockets outlive the component that made them.",
        ),
        q(
            Topic.RUNTIME,
            "What is a detached DOM node?",
            "an element off the page that code still holds",
            "an element that failed to render",
            "It is the classic sign of a listener or closure hanging on.",
        ),
        q(
            Topic.RUNTIME,
            "How do you actually find a memory leak?",
            "two heap snapshots in the same state, compared",
            "watch the frame rate",
            "Go to the same screen twice. Whatever grew is your suspect.",
        ),
        q(
            Topic.RUNTIME,
            "Why does a cache at the top of a file leak?",
            "it lives as long as the page and never empties",
            "it gets cleared per route",
            "That scope is basically global. Unbounded means unbounded.",
        ),
        q(
            Topic.RUNTIME,
            "What is this in a plain function call?",
            "undefined in strict mode",
            "the surrounding object",
            "Pull a method off an object and this is gone. Hence bind and arrow fields.",
        ),
        q(
            Topic.RUNTIME,
            "What is this inside an arrow function?",
            "whatever it was where you wrote it",
            "decided when it is called",
            "call and bind cannot change it. That is both the point and the trap.",
        ),
        q(
            Topic.RUNTIME,
            "An arrow function as a class field creates what?",
            "one function per instance",
            "one shared function",
            "That is the memory you pay for automatic binding.",
        ),
        q(
            Topic.RUNTIME,
            "What do generators let you do?",
            "pause and resume a function",
            "run on another thread",
            "Still one thread. It is lazy control flow, not concurrency.",
        ),
        q(
            Topic.RUNTIME,
            "What are async iterators good for?",
            "streams and paged data",
            "heavy loops",
            "for await over pages hides the cursor without blocking anything.",
        ),
        q(
            Topic.RUNTIME,
            "What cannot be structurally cloned?",
            "functions and DOM nodes",
            "Maps and Sets",
            "Maps, Sets and Dates copy fine. Functions and elements do not.",
        ),
        q(
            Topic.RUNTIME,
            "What does postMessage send?",
            "a copy",
            "the original object",
            "Unless you transfer a buffer, which hands it over and empties your side.",
        ),
        q(
            Topic.RUNTIME,
            "Is there a good use for double equals?",
            "x == null, to catch null and undefined",
            "no, never",
            "It is the one coercion that is deliberate and readable.",
        ),
        q(
            Topic.RUNTIME,
            "What does a closure hold onto?",
            "the variable itself",
            "a copy of its value",
            "It is why var in a loop gave every callback the final number.",
        ),
        q(
            Topic.RUNTIME,
            "You wrap a promise you did not await in try catch. What is caught?",
            "nothing",
            "the rejection",
            "The failure happens after the block ended. No await, nothing to catch it.",
        ),
        q(
            Topic.RUNTIME,
            "An async function throws. What does the caller see?",
            "a rejected promise",
            "a thrown error",
            "You have to await it or catch it. It never lands on the normal stack.",
        ),
        q(
            Topic.RUNTIME,
            "How do you starve the event loop?",
            "microtasks that keep queueing microtasks",
            "too many timers",
            "Timers let the browser breathe. An endless promise chain does not.",
        ),
        q(
            Topic.RUNTIME,
            "How deep does object spread copy?",
            "one level",
            "all the way down",
            "Nested objects are still shared, which is how mutations sneak across.",
        ),
        q(
            Topic.RUNTIME,
            "When does requestAnimationFrame run?",
            "just before the next frame is drawn",
            "every 16ms",
            "It follows the frame, so it stops in a background tab.",
        ),
        q(
            Topic.RUNTIME,
            "You set a style, then read offsetHeight. What happens?",
            "the browser has to lay out right then",
            "nothing special",
            "Do that in a loop and it is layout thrashing. Read everything first, then write.",
        ),

        q(
            Topic.DESIGN,
            "Collaborative editing. What do you do with a keystroke?",
            "show it now, settle with the server after",
            "wait for the server to confirm it",
            "Waiting on every keystroke feels broken on any real connection.",
        ),
        q(
            Topic.DESIGN,
            "Realtime events arrive out of order. Now what?",
            "put a version on each one and drop the old",
            "trust the order they arrived in",
            "Reconnects deliver the past. Only a number tells you which one is newer.",
        ),
        q(
            Topic.DESIGN,
            "The socket dropped and came back. What do you do?",
            "refetch, or replay from the last one you got",
            "carry on with what you have",
            "You have no idea what you missed. Assume you missed something.",
        ),
        q(
            Topic.DESIGN,
            "What does composition over configuration mean?",
            "small pieces the caller puts together",
            "more props with good defaults",
            "One component with a flag per variation only ever grows.",
        ),
        q(
            Topic.DESIGN,
            "A component has thirty props. What does that tell you?",
            "it is several components in one",
            "it is well documented",
            "The prop count is the symptom. Doing several jobs is the cause.",
        ),
        q(
            Topic.DESIGN,
            "What do headless component libraries give you?",
            "behavior and accessibility, no styling",
            "server and client separation",
            "You get the keyboard and screen reader work without their look.",
        ),
        q(
            Topic.DESIGN,
            "Rolling out a new design system across 400 files. How?",
            "run both and migrate a bit at a time",
            "one branch that changes everything",
            "A giant branch cannot be reviewed or released, so it never lands.",
        ),
        q(
            Topic.DESIGN,
            "What goes wrong with shared UI in a monorepo?",
            "one change forces everyone to release",
            "slower type checking",
            "Teams end up waiting on each other to ship.",
        ),
        q(
            Topic.DESIGN,
            "Removing a component twelve teams use. How?",
            "warn, give them a codemod, set a date",
            "delete it and tell them",
            "A migration you do not automate does not happen.",
        ),
        q(
            Topic.DESIGN,
            "A form with forty fields. How do you keep typing fast?",
            "one keystroke touches one field",
            "keep the form object in context",
            "Uncontrolled fields keep the rest of the tree out of the way.",
        ),
        q(
            Topic.DESIGN,
            "Client validation and server validation. How do they relate?",
            "the server decides, the client just hints",
            "same rules, trust the client",
            "Client checks are for fast feedback. They guarantee nothing.",
        ),
        q(
            Topic.DESIGN,
            "How do you stop feature flags piling up forever?",
            "every flag gets an owner and a date",
            "keep them, you may toggle later",
            "Each flag is another live branch inside your code.",
        ),
        q(
            Topic.DESIGN,
            "Where is the most test value per hour?",
            "integration tests with a fake network",
            "a unit test per function",
            "They cover the wiring, which is where React apps actually break.",
        ),
        q(
            Topic.DESIGN,
            "What do you deliberately not test?",
            "internals, like how many times it rendered",
            "error and empty states",
            "Tests tied to internals block refactors and catch nothing real.",
        ),
        q(
            Topic.DESIGN,
            "Where do error boundaries go?",
            "around each part that can fail on its own",
            "one at the root",
            "Only at the root means one broken widget blanks the whole page.",
        ),
        q(
            Topic.DESIGN,
            "What do error boundaries miss?",
            "errors in event handlers and async code",
            "errors while rendering",
            "They only see rendering and lifecycle.",
        ),
        q(
            Topic.DESIGN,
            "A custom dropdown needs what most?",
            "focus and keyboard handling",
            "the right role attribute",
            "Roles describe. They do not make anything work, and a wrong one is worse.",
        ),
        q(
            Topic.DESIGN,
            "What is roving tabindex for?",
            "one tab stop, then arrows inside",
            "skip to content links",
            "A toolbar or a grid should be one stop, not forty.",
        ),
        q(
            Topic.DESIGN,
            "What is an aria live region for?",
            "announcing things the user did not trigger",
            "labelling an element",
            "Toasts and background updates are silent without it.",
        ),
        q(
            Topic.DESIGN,
            "What does a modal have to do?",
            "trap focus, put it back, hide the rest",
            "focus the first input",
            "Returning focus to the button that opened it is the part everyone skips.",
        ),
        q(
            Topic.DESIGN,
            "Streaming plus error boundaries gives you what?",
            "one broken section, the rest still fine",
            "the whole page falls back",
            "That is the payoff for boundaries around each independent region.",
        ),
        q(
            Topic.DESIGN,
            "Best reason to move code into a shared package?",
            "the behavior must not drift apart",
            "it is duplicated",
            "Duplication is cheap. Two copies behaving differently is not.",
        ),

        q(
            Topic.DEBUG,
            "First thing you do with any bug?",
            "make it happen on demand",
            "read the code until you spot it",
            "Otherwise you cannot tell if you fixed it or just moved the symptom.",
        ),
        q(
            Topic.DEBUG,
            "Works locally, breaks in production. What do you look at?",
            "what differs: build, env, data, caching",
            "the feature code",
            "The code is identical. Start with what is not.",
        ),
        q(
            Topic.DEBUG,
            "A fix with no reproduction is what?",
            "a guess",
            "fine if the tests pass",
            "Green tests that never covered the bug prove nothing about it.",
        ),
        q(
            Topic.DEBUG,
            "It only happens for one customer. What do you assume?",
            "their data or their settings",
            "their browser is broken",
            "Get their exact state. It is almost always the data.",
        ),
        q(
            Topic.DEBUG,
            "Why is bisecting so useful?",
            "it finds the commit without reading the code",
            "it fixes the regression",
            "It turns an open ended hunt into a handful of builds.",
        ),
        q(
            Topic.DEBUG,
            "No tests, and someone wants a rewrite. What do you say?",
            "test what it does now, then change it in place",
            "rewrite it, it is beyond saving",
            "A rewrite loses behavior nobody wrote down, and you find out in production.",
        ),
        q(
            Topic.DEBUG,
            "How do you know an abstraction is wrong?",
            "every new case needs another flag",
            "the file got long",
            "The options list growing with every caller is the tell.",
        ),
        q(
            Topic.DEBUG,
            "How do you undo a bad abstraction?",
            "copy it back out, then look again",
            "add an option for the new case",
            "Let the real pattern show itself instead of guessing a second time.",
        ),
        q(
            Topic.DEBUG,
            "The bug disappears when you add a log. What is it?",
            "timing",
            "a compiler bug",
            "The log changed the timing. Go looking for a race.",
        ),
        q(
            Topic.DEBUG,
            "The fix is in. What is left?",
            "a test for the case that failed",
            "nothing, close the ticket",
            "Otherwise it comes back in six months and nobody notices.",
        ),
        q(
            Topic.DEBUG,
            "On a performance question, what is the interviewer listening for?",
            "how you would find out",
            "the optimizations you know",
            "Measuring before optimizing is the actual senior signal.",
        ),
        q(
            Topic.DEBUG,
            "Something fails now and then. What do you ask first?",
            "what do the failures have in common",
            "how do I retry it",
            "Intermittent means something hidden is changing. Find that first.",
        ),

        q(
            Topic.CODE,
            "A debounced autocomplete needs which states?",
            "loading, empty, error and cancelled",
            "just the results",
            "The ones you skip are exactly the ones being watched for.",
        ),
        q(
            Topic.CODE,
            "How should an autocomplete handle the keyboard?",
            "arrows move a highlight, enter picks, escape closes",
            "tab through the options",
            "Tab has to leave the widget. Moving around inside is arrows.",
        ),
        q(
            Topic.CODE,
            "You are writing useQuery. How do you avoid fetching twice?",
            "keep running requests by key and share them",
            "an isLoading flag",
            "Two components mounting together should join one request.",
        ),
        q(
            Topic.CODE,
            "How do you build infinite scroll?",
            "watch an empty element after the last row",
            "listen to scroll and do the maths",
            "The observer tells you when it comes into view. No measuring needed.",
        ),
        q(
            Topic.CODE,
            "Why is that better than a scroll handler?",
            "it does not run while you scroll",
            "less code",
            "No throttling, and no measuring the page on every frame.",
        ),
        q(
            Topic.CODE,
            "What does a focus trap have to do?",
            "loop tab both ways, give focus back on close",
            "block the tab key",
            "Blocking tab strands keyboard users inside with no way out.",
        ),
        q(
            Topic.CODE,
            "Where does the escape key listener go?",
            "on the dialog, removed when it closes",
            "on document, and left there",
            "One left behind will close the next dialog too.",
        ),
        q(
            Topic.CODE,
            "What should a drag handle listen to?",
            "pointer events, with capture",
            "mousemove",
            "Capture keeps the drag alive when the cursor outruns the handle, and covers touch.",
        ),
        q(
            Topic.CODE,
            "debounce with cancel and flush has to keep what?",
            "the timer and the last arguments",
            "a shared map",
            "Each debounced function owns its own pending call.",
        ),
        q(
            Topic.CODE,
            "What makes deepEqual hard?",
            "cycles, NaN, Date and Map",
            "nested objects",
            "The plain cases are easy. Cycles are where the naive version hangs forever.",
        ),
        q(
            Topic.CODE,
            "How do you type an event emitter?",
            "a map of event name to payload",
            "any",
            "That map is what keeps emit and on from drifting apart.",
        ),
        q(
            Topic.CODE,
            "Five effects in one component usually means what?",
            "values are being copied into state",
            "it genuinely does five things",
            "Most of them turn back into plain calculations.",
        ),
        q(
            Topic.CODE,
            "First question when cleaning up an effect?",
            "is it talking to something outside React",
            "can I merge the deps lists",
            "If it is not, it should not be an effect at all.",
        ),
        q(
            Topic.CODE,
            "throttle or debounce?",
            "throttle fires regularly, debounce waits for a pause",
            "same thing",
            "Throttle when you want steady updates, debounce when only the last counts.",
        ),
        q(
            Topic.CODE,
            "What must a useFetch cleanup do?",
            "abort or ignore the request in flight",
            "clear the loading flag",
            "Otherwise a late reply sets state on something that already moved on.",
        ),
        q(
            Topic.CODE,
            "A custom hook returns an object. What matters?",
            "it stays the same object between renders",
            "it is rebuilt each time to stay fresh",
            "An unstable return breaks every deps list downstream.",
        ),
    )
}
