package com.abhiram.devquiz

internal fun q(topic: Topic, code: String, prompt: String, correct: String, wrong: String, why: String) =
    Question(topic, code, prompt, correct, wrong, why)

object TsQuestions {

    val all: List<Question> = tsBasics + tsTypes + tsNarrow + tsGeneric + tsAsync + tsArray + tsObject
}

internal val tsBasics: List<Question> = listOf(

    q(
        Topic.BASICS,
        "const a = '5' + 3",
        "a is?",
        "'53'",
        "8",
        "A string on either side of + turns it into concatenation.",
    ),
    q(
        Topic.BASICS,
        "const a = '5' - 3",
        "a is?",
        "2",
        "'2'",
        "Only + concatenates. The other math operators force numbers.",
    ),
    q(
        Topic.BASICS,
        "typeof null",
        "Result?",
        "'object'",
        "'null'",
        "A bug from 1995 that can never be fixed. Check with x === null.",
    ),
    q(
        Topic.BASICS,
        "typeof []",
        "Result?",
        "'object'",
        "'array'",
        "Arrays are objects. Use Array.isArray to test for one.",
    ),
    q(
        Topic.BASICS,
        "typeof NaN",
        "Result?",
        "'number'",
        "'NaN'",
        "NaN is a number value meaning 'this math failed'.",
    ),
    q(
        Topic.BASICS,
        "NaN === NaN",
        "Result?",
        "false",
        "true",
        "NaN equals nothing, itself included. Use Number.isNaN.",
    ),
    q(
        Topic.BASICS,
        "0.1 + 0.2 === 0.3",
        "Result?",
        "false",
        "true",
        "Binary floats cannot hold 0.1 exactly. Compare with a small tolerance.",
    ),
    q(
        Topic.BASICS,
        "null == undefined\nnull === undefined",
        "The two lines give?",
        "true, then false",
        "true, then true",
        "== treats null and undefined as equal. === compares the type too.",
    ),
    q(
        Topic.BASICS,
        "const x = 0 || 'hi'",
        "x is?",
        "'hi'",
        "0",
        "|| falls through on any falsy value, and 0 is falsy.",
    ),
    q(
        Topic.BASICS,
        "const x = 0 ?? 'hi'",
        "x is?",
        "0",
        "'hi'",
        "?? only falls through on null or undefined, so 0 survives.",
    ),
    q(
        Topic.BASICS,
        "const x = ''\n  || 'fallback'\nconst y = ''\n  ?? 'fallback'",
        "x and y?",
        "'fallback' and ''",
        "'fallback' and 'fallback'",
        "Empty string is falsy but it is not null, so ?? keeps it.",
    ),
    q(
        Topic.BASICS,
        "Boolean('0')",
        "Result?",
        "true",
        "false",
        "Every non empty string is truthy, whatever is in it.",
    ),
    q(
        Topic.BASICS,
        "Boolean([])",
        "Result?",
        "true",
        "false",
        "Every object and array is truthy, even an empty one.",
    ),
    q(
        Topic.BASICS,
        "Number('')",
        "Result?",
        "0",
        "NaN",
        "Empty string converts to 0. 'abc' is the one that gives NaN.",
    ),
    q(
        Topic.BASICS,
        "const a = { n: 1 }\na.n = 2",
        "Legal with const?",
        "yes, it runs",
        "no, TypeScript errors",
        "const locks the binding, not the contents. Use readonly to lock fields.",
    ),
    q(
        Topic.BASICS,
        "let a = [1, 2]\nconst b = a\nb.push(3)\na.length",
        "Result?",
        "3",
        "2",
        "b is the same array, not a copy. Copy with [...a].",
    ),
    q(
        Topic.BASICS,
        "'abc'.at(-1)",
        "Result?",
        "'c'",
        "undefined",
        "at accepts negative indexes and counts from the end.",
    ),
    q(
        Topic.BASICS,
        "'a,b,,c'\n  .split(',').length",
        "Result?",
        "4",
        "3",
        "split keeps the empty piece between the two commas.",
    ),
    q(
        Topic.BASICS,
        "const [a, b = 9] = [1]",
        "b is?",
        "9",
        "undefined",
        "A destructuring default fires when the value is undefined.",
    ),
    q(
        Topic.BASICS,
        "const { a = 9 } =\n  { a: null }",
        "a is?",
        "null",
        "9",
        "Defaults only cover undefined. null is a real value and passes through.",
    ),
    q(
        Topic.BASICS,
        "const s = 'hi'\ns.length",
        "s.toUpperCase() changes s?",
        "no, strings never change",
        "yes, in place",
        "String methods return a new string. The original is immutable.",
    ),
    q(
        Topic.BASICS,
        "const n = 5\nn.toFixed(2)",
        "Result?",
        "'5.00'",
        "5.00",
        "toFixed returns a string, so it is a common source of '5.00' + 1.",
    ),
    q(
        Topic.BASICS,
        "parseInt('12px')",
        "Result?",
        "12",
        "NaN",
        "parseInt reads digits until it hits junk. Number('12px') is NaN.",
    ),
    q(
        Topic.BASICS,
        "[10, 9, 1].sort()",
        "Result?",
        "[1, 10, 9]",
        "[1, 9, 10]",
        "Default sort compares text. Pass (a, b) => a - b for numbers.",
    ),
    q(
        Topic.BASICS,
        "const a = [3, 1]\na.sort()\na",
        "a is?",
        "[1, 3], a changed",
        "[3, 1], sort returns a copy",
        "sort mutates in place. Use [...a].sort() to keep the original.",
    ),
    q(
        Topic.BASICS,
        "typeof (() => {})",
        "Result?",
        "'function'",
        "'object'",
        "Functions are the one callable object with their own typeof.",
    ),
    q(
        Topic.BASICS,
        "const x = [1, 2] + [3]",
        "x is?",
        "'1,23'",
        "[1, 2, 3]",
        "+ turns both arrays into strings first. Use concat or spread.",
    ),
    q(
        Topic.BASICS,
        "1 < 2 < 3\n3 > 2 > 1",
        "The two lines give?",
        "true, then false",
        "true, then true",
        "It reads left to right, so the second becomes true > 1, which is 1 > 1.",
    ),
    q(
        Topic.GOTCHA,
        "const f = () => {\n  return\n    { ok: true }\n}",
        "f() returns?",
        "undefined",
        "{ ok: true }",
        "A newline after return ends the statement. Keep the brace on the same line.",
    ),
    q(
        Topic.GOTCHA,
        "['1', '7', '11']\n  .map(parseInt)",
        "Result?",
        "[1, NaN, 3]",
        "[1, 7, 11]",
        "map passes the index as the radix. Write map(s => parseInt(s, 10)).",
    ),
    q(
        Topic.GOTCHA,
        "const o = {}\no.a?.b",
        "Result?",
        "undefined",
        "a TypeError",
        "?. stops and gives undefined the moment the left side is null or undefined.",
    ),
    q(
        Topic.GOTCHA,
        "const o = { a: 0 }\no.a?.toFixed(1)",
        "Result?",
        "'0.0'",
        "undefined",
        "?. only short circuits on null or undefined, and 0 is neither.",
    ),
    q(
        Topic.GOTCHA,
        "const a = { x: 1 }\nconst b = { x: 1 }\na === b",
        "Result?",
        "false",
        "true",
        "Objects compare by identity, never by contents.",
    ),
    q(
        Topic.GOTCHA,
        "const s =\n  new Set([1, 1, 2])\ns.size",
        "Result?",
        "2",
        "3",
        "A Set drops duplicates, using === style identity.",
    ),
    q(
        Topic.GOTCHA,
        "const s = new Set([\n  {a:1}, {a:1}])\ns.size",
        "Result?",
        "2",
        "1",
        "Two objects with equal fields are still two different identities.",
    ),
    q(
        Topic.GOTCHA,
        "const a = [1, 2, 3]\na.length = 1\na",
        "a is?",
        "[1]",
        "[1, 2, 3]",
        "Writing length truncates the array for real.",
    ),
    q(
        Topic.GOTCHA,
        "const d =\n  new Date(2024, 0, 1)",
        "Which month?",
        "January",
        "February",
        "Date months are zero based. Day and year are not.",
    ),
    q(
        Topic.GOTCHA,
        "const x = JSON.parse(\n  JSON.stringify(\n    { d: new Date() }))",
        "x.d is?",
        "a string",
        "a Date",
        "That clone trick loses Dates, Maps, undefined and functions.",
    ),
    q(
        Topic.GOTCHA,
        "JSON.stringify(\n  { a: undefined })",
        "Result?",
        "'{}'",
        "'{\"a\":undefined}'",
        "stringify drops undefined fields entirely. null is kept.",
    ),
    q(
        Topic.GOTCHA,
        "for (var i = 0; i < 3;\n     i++)\n  setTimeout(() =>\n    log(i))",
        "It logs?",
        "3 3 3",
        "0 1 2",
        "var is one shared binding. let gives each loop turn its own.",
    ),
    q(
        Topic.GOTCHA,
        "const o = { n: 1,\n  get(){return this.n}}\nconst g = o.get\ng()",
        "Result?",
        "throws or undefined",
        "1",
        "this comes from the call site. Pulling the method off loses the receiver.",
    ),
    q(
        Topic.GOTCHA,
        "class A {\n  n = 1\n  get = () => this.n\n}",
        "Passing a.get around?",
        "still works",
        "loses this",
        "An arrow field captures this at construction, so it is safe to pass.",
    ),
    q(
        Topic.GOTCHA,
        "let x = 1\nconst f = () => x\nx = 2\nf()",
        "Result?",
        "2",
        "1",
        "A closure captures the variable, not a snapshot of its value.",
    ),
    q(
        Topic.GOTCHA,
        "[1, 2, 3].map(\n  n => { n * 2 })",
        "Result?",
        "[undefined, undefined, undefined]",
        "[2, 4, 6]",
        "Braces make it a body, not an expression. Drop them or add return.",
    ),
    q(
        Topic.GOTCHA,
        "const f = () =>\n  ({ ok: true })",
        "Why the parens?",
        "so the braces mean an object",
        "purely style",
        "Without them the braces read as a function body and it returns undefined.",
    ),
    q(
        Topic.GOTCHA,
        "if (arr.length = 0) {}",
        "What happens?",
        "it assigns, then is falsy",
        "it compares to 0",
        "One = is assignment. It also just emptied the array.",
    ),
    q(
        Topic.GOTCHA,
        "const n = Number(null)\nconst u =\n  Number(undefined)",
        "n and u?",
        "0 and NaN",
        "NaN and NaN",
        "null converts to 0, undefined does not convert at all.",
    ),
    q(
        Topic.GOTCHA,
        "'2' > '10'",
        "Result?",
        "true",
        "false",
        "Two strings compare character by character, so '2' beats '1'.",
    ),
    q(
        Topic.GOTCHA,
        "const a = [,]\na.length",
        "Result?",
        "1",
        "2",
        "A single trailing comma is ignored, so it is one hole, not two.",
    ),
    q(
        Topic.GOTCHA,
        "structuredClone(obj)",
        "Compared to a spread copy?",
        "deep, nested objects too",
        "shallow, same as spread",
        "Spread copies one level. structuredClone walks the whole tree.",
    ),
)
